/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "ring": "戒指",
    "ring slot": "戒指槽位",
    "Stats": "统计",
    "Tools": "工具",
    "Type:": "类型:",
    "Total cost:": "总计成本:",
    "torso slot": "躯干槽位",
    "Your feet slot": "你的脚部槽位",
    "Your off-hand slot": "你的副手槽位",
    "Your legs slot": "你的腿部槽位",
    "Your torso slot": "你的躯干槽位",
    "Your ring slot": "你的戒指槽位",
    "Your head slot": "你的头部槽位",
    "Your arms slot": "你的手臂槽位",
    "Your amulet slot": "你的护身符槽位",
    "amulet": "护身符",
    "amulet slot": "护身符槽位",
    "weapon": "武器",
    "Strength:": "力量:",
    "sword": "剑",
    "other": "其它",
    "Other": "其它",
    "off-hand": "副手",
    "off-hand slot": "副手槽位",
    "Sort by level": "按等级排序",
    "Sort by name": "按名称排序",
    "Sort by value": "按价值排序",
    "Stale bread": "不太新鲜的面包",
    "torso": "躯干",
    "Village": "村庄",
    "Your agility. It affects your evasion chance": "你的敏捷性。 会影响你的闪避几率",
    "Your chance for critical attack": "你的暴击几率",
    "Your defense. Based on worn equipment, lowers damage taken": "你的防御。 根据磨损的装备，降低受到的伤害",
    "= Skills =": "= 技能 =",
    "= Quests =": "= 任务 =",
    "= Data =": "= 数据 =",
    "= Bestiary =": "= 动物寓言 =",
    "Your strength. It affects power of physical attacks": "你的力量。 影响物理攻击力",
    "Your magic power. It affects damage of magic attacks": "你的魔法力。 影响魔法攻击的伤害",
    "Your intuition. It's necessary for magic, while also providing slight bonus to hit chance and evasion": "你的直觉。 它对于魔法来说是必需的，同时也为命中率和闪避提供了轻微的奖励",
    "Your dexterity. It affects your chance to hit target": "你的灵巧。 它会影响你击中目标的机会",
    "Usable": "可用",
    "usable": "可用",
    "Slot:": "槽位:",
    "Ability to see in darkness": "在黑暗中看得见的能力",
    "arms": "手臂",
    "head slot": "头部槽位",
    "arms slot": "手臂槽位",
    "Area / Combat": "区域 / 战斗",
    "Cancel": "取消",
    "Character": "角色",
    "iron sword": "铁剑",
    "hat": "帽",
    "pants": "裤",
    "leather pants": "皮裤",
    "Data": "数据",
    "equipment": "装备",
    "Equipment": "装备",
    "head": "头部",
    "Intuition": "直觉",
    "legs slot": "腿部槽位",
    "legs": "腿部",
    "Loot": "战利品",
    "Levels and unlocks": "等级和解锁",
    "Exit": "退出",
    "feet slot": "脚部槽位",
    "feet": "脚部",
    "Magic:": "魔法:",
    "Prices:": "价格:",
    "Quests": "任务",
    "Talk to the village elder": "与村长交谈",
    "Return to last bed upon defeat": "失败后返回上一张床",
    "Remember message log filters": "记住消息日志过滤器",
    "Reduces darkness penalty (except for 'pure darkness') by 70%": "减少 70% 的黑暗惩罚（“纯粹黑暗”除外）",
    "Evasion points, a total value of everything that contributes to the evasion chance, except for some situational skills and modifiers": "躲避点数，所有有助于躲避几率的总价值，除了一些情境技能和修饰符之外",
    "Dexterity:": "灵巧：",
    "Damage of your critical attacks": "你的暴击造成的伤害",
    "Crit rate:": "暴击率:",
    "Combat": "战斗",
    "Medium-sized village surrounded by many fields, some of them infested by rats. Other than that, there's nothing interesting around.": "中等规模的村庄，周围有许多田地，其中一些田地里老鼠出没。 除此之外，周围没有什么有趣的事情。",
    "Base hero xp gain:": "基础英雄经验增益：",
    "Base skill xp gain:": "基础技能经验增益：",
    "Crit mult:": "暴击乘数:",
    "Big piece of an old bread, still edible": "一大块旧面包，还能吃",
    "Bestiary": "动物寓言",
    "normal stance": "正常姿态",
    "Defense:": "防御:",
    "Events": "事件",
    "Force uniform size of text in action box": "强制操作框中的文本大小统一",
    "Hard reset the game": "硬重置",
    "Accept": "同意",
    "Active effects:": "当前效果：",
    "Agility:": "敏捷:",
    "all": "全部",
    "Attack speed. Directly affects the attack frequency": "攻击速度。 直接影响攻击频率",
    "Attack power. Based on weapon statistics, strength and/or magic": "攻击力。 基于武器属性、力量和/或魔法",
    "Increases stamina regeneration by +1 for 60 ticks": "60 秒内耐力再生增加 +1",
    "No active effects": "无",
    "Reduces darkness penalty (except for 'pure darkness') by 80%": "黑暗惩罚（“纯粹黑暗”除外）减少 80%",
    "Atk power:": "攻击力：",
    "EP :": "闪避点：",
    "AP:": "攻击力：",
    "We don't have anything to spare, but you can talk with our trader. He should be somewhere nearby. If you need money, try selling him some rat remains. Fangs, tails or pelts, he will buy them all. I have no idea what he does with this stuff...": "我们没有多余的东西，但你可以和我们的商人谈谈。 他应该就在附近的某个地方。 如果你需要钱，可以尝试卖给他一些老鼠残骸。 獠牙、尾巴、毛皮，他都会买下来。 我不知道他用这些东西做什么...",
    "Oh yes, quite a big one. Not literally, no, though they are much larger than normal rats... They are a nasty vermin that's really hard to get rid of. And with their numbers they can be seriously life-threatening. Only in a group though, single wolf rat is not much of a threat": "哦，是的，相当大的一个。 不是字面意义上的，不，尽管它们比普通老鼠大得多……它们是一种令人讨厌的害虫，很难摆脱。 由于数量众多，它们可能会严重危及生命。 不过，只有在群体中，单个狼鼠才不会构成太大的威胁",
    "What you need is to recover, to get some rest and maybe also training, as you seem rather frail... Well, you know what? Killing a few wolf rats could be a good exercise. You could help us clear some field of them, how about that?": "你需要的是恢复、休息，也许还需要训练，因为你看起来很虚弱……好吧，你知道吗？ 杀死几只狼鼠可能是一个很好的练习。 你可以帮我们清理一些田野，怎么样？",
    "\"Are there other ways to make money?\"": "“还有其他赚钱的方法吗？”",
    "\"Are wolf rats a big issue?\"": "“狼鼠是个大问题吗？”",
    "\"But I need to leave\"": "“但我需要离开”",
    "\"Can I leave the village?\"": "“我可以离开村子吗？”",
    "\"Great... Thank you for help, but I will leave now.\"": "“太好了……谢谢你的帮助，但我现在就走了。”",
    "\"Hello?\"": "\“你好？\”",
    "\"I don't remember how I got here, what happened?\"": "“我不记得我是怎么来到这里的，发生了什么？”",
    "\"Is there any way I could get a weapon and proper clothes?\"": "“我有什么办法可以获得武器和合适的衣服吗？”",
    "\"Who are you?\"": "\“你是谁？\”",
    "Available from 6 to 20": "6 至 20 可用",
    "Go back": "返回",
    "Go for a run around the village": "绕村子跑一圈",
    "Hello. Glad to see you got better": "你好。 很高兴看到你好起来",
    "I'm the unofficial leader of this village. If you have any questions, come to me": "我是这个村子的非正式领导。 如果您有任何疑问，请来找我",
    "Nearby lands are dangerous and you are still too weak to leave. Do you plan on getting ambushed again?": "附近的土地很危险，而你仍然太虚弱，无法离开。 你还打算再次遭到伏击吗？",
    "Pays 1": "支付 1",
    "per every 2 h worked": "每工作 2 小时",
    "Some of our people found you unconscious in the forest, with nothing but pants. Must have been bandits.": "我们的一些人发现你在森林里昏迷不醒，除了裤子什么也没有。 一定是土匪。",
    "Trade with village trader": "与村庄商人进行交易",
    "Try to carry some bags of grain": "尝试搬运几袋粮食",
    "Unlocked activity \"plowing the fields\" in location \"Village\"": "解锁地点“村庄”的活动“耕作”",
    "Unlocked activity \"running\" in location \"Village\"": "在位置“村庄”解锁活动“跑步”",
    "Unlocked activity \"weightlifting\" in location \"Village\"": "在地点“村庄”解锁活动“举重”",
    "Unlocked location Infested field": "解锁地点 被感染的田野",
    "We talked about this, you are still too weak": "我们谈过这个了，你还是太弱了",
    "Work on the fields": "耕作",
    "You can now trade with village trader": "您现在可以与村庄商人进行交易",
    "You could help us with some fieldwork. I'm afraid it won't pay too well.": "你可以帮助我们进行一些耕作。 恐怕报酬不会太高。",
    "Finish running": "完成跑步",
    "Finish weightlifting": "完成举重",
    "axe": "斧子",
    "battle hammer": "战锤",
    "spear": "矛",
    "Increases health regeneration by +1 for 120 ticks": "120 秒内生命恢复 +1",
    "Increases stamina regeneration by +1 for 120 ticks": "120 秒内耐力恢复 +1",
    "shield": "盾牌",
    "\"ABC for kids\"": "“儿童ABC”",
    "\"Old combat manual\"": "《旧作战手册》",
    "ABC for kids": "儿童ABC",
    "Fresh bread": "新鲜的面包",
    "Freshly baked bread, delicious": "新鲜出炉的面包，好吃",
    "hammer": "锤子",
    "vest": "背心",
    "leather vest": "皮背心",
    "Not very potent, but can still make body heal noticeably faster": "不是很有效，但仍然可以使身体愈合得明显更快",
    "nothing": "没有什么",
    "Old book about combat, worn and outdated, but might still contain something useful": "关于战斗的旧书，破旧过时，但可能仍然包含一些有用的东西",
    "Old combat manual": "旧的战斗手册",
    "The simplest book on the market": "市面上最简单的书",
    "Weak healing powder": "弱治愈粉",
    "A completely open area where attack can come from any direction": "完全开放的区域，攻击可以来自任何方向",
    "Attack power:": "攻击力：",
    "Attack speed:": "攻击速度：",
    "base %": "根据 ％",
    "current %": "当前的 ％",
    "Field infested with wolf rats. You can see the grain stalks move as these creatures scurry around.": "田野里满是狼鼠。 当这些生物四处奔走时，您可以看到谷物秸秆移动。",
    "Go back to Village": "回到村庄",
    "Health:": "生命值：",
    "Hero evaded an attack": "英雄躲避了攻击",
    "Increases xp gains of all weapon skills of level lower than this, x1.1 per level of difference": "增加低于此等级的所有武器技能的经验值增益，每级差异 x1.1",
    "Infested field": "被感染的田地",
    "Item name": "物品名称",
    "Loot list:": "战利品清单：",
    "Mastery of all weapons": "精通所有武器",
    "open": "开放",
    "Overall combat ability": "综合作战能力",
    "Rat fang": "鼠牙",
    "Rat pelt": "鼠皮",
    "Rat tail": "鼠尾",
    "Rat with size of a dog, starved and weakened": "老鼠大小如狗，饥饿且虚弱",
    "Reduces environmental penalty in open areas by 0%": "开放区域的环境惩罚减少 0%",
    "Small enemies might not seem very dangerous, but it's not that easy to hit them!": "小敌人看似不太危险，但想要击中却可没那么容易！",
    "Starving wolf rat": "饥饿的狼鼠",
    "Starving wolf rat was defeated": "饥饿的狼鼠被击败",
    "Stats:": "统计：",
    "The noble art of swordsmanship": "高贵的剑术",
    "Understanding where you are in relation to other creatures and objects": "了解您相对于其他生物和物体的位置",
    "Combat": "战斗",
    "Pest killer": "害虫杀手",
    "Spatial awareness": "空间感知",
    "Swordsmanship": "剑术",
    "Weapon mastery": "武器精通",
    "Wolf": "狼",
    "Wolf rat": "狼鼠",
    "Great way to improve the efficiency of the body": "提高身体效率的好方法",
    "Running": "跑步",
    "Thanks to Running reaching new milestone, Hero gained:": "由于跑步达到新的里程碑，英雄获得了：",
    "Finish plowing the fields": "完成耕作",
    "plowing the fields": "耕作",
    "Even a simple action of plowing some fields, can be performed better with skills and experience": "即使是耕田这样一个简单的动作，通过技巧和经验也可以做得更好",
    "weapon slot": "武器槽",
    "Your weapon slot": "你的武器槽",
    "No better way to get stronger than by lifting heavy things": "没有比举重物更好的增强力量的方法了",
    "Thanks to Weightlifting reaching new milestone, Hero gained:": "由于举重达到了新的里程碑，英雄获得了：",
    "Ability to evade attacks": "躲避攻击的能力",
    "weightlifting": "举重",
    "Weightlifting": "举重",
    "Evasion": "闪避",
    "Rat with size of a dog": "老鼠有狗那么大",
    "Wolf rat was defeated": "狼鼠被击败了",
    "Thanks to Swordsmanship reaching new milestone, Hero gained:": "由于剑术达到了新的里程碑，英雄获得了：",
    "Thanks to Evasion reaching new milestone, Hero gained:": "由于闪避达到了新的里程碑，英雄获得了：",
    "Fang of a huge rat, not very sharp, but can still pierce a human skin if enough force is applied": "巨大老鼠的尖牙，不是很锋利，但如果用力足够，仍然可以刺穿人的皮肤",
    "Thanks to Pest killer reaching new milestone, Hero gained:": "由于害虫杀手达到了新的里程碑，英雄获得了：",
    "Maybe you should check on village elder...": "或许你应该去问问村长...",
    "Being tired is not a reason to give up": "累不是放弃的理由",
    "Tail of a huge rat, doesn't seem very useful, but maybe someone would buy it": "大老鼠的尾巴，看起来没什么用，但也许会有人买",
    "You did? That's good. How about a stronger target? Nearby cave is just full of this vermin. Before that, maybe get some sleep? Some folks prepared that shack over there for you. It's clean, it's dry, and it will give you some privacy.": "你做到了吗？ 那挺好的。 更强大的目标怎么样？ 附近的洞穴里充满了这种害虫。 在那之前，也许先睡一会儿？ 那边有人为你准备了那个小屋。 它干净、干燥，而且会给你一些隐私。",
    "\"I cleared the field, just as you asked me to\"": "“我按照你的要求清理了田野”",
    "A big cave near the village, once used as a storeroom. Groups of fluorescent mushrooms cover the walls, providing a dim light. You can hear sounds of rats from.": "村子附近的一个大山洞，曾经被用作储藏室。 成群的荧光蘑菇覆盖在墙壁上，发出昏暗的光线。 你可以听到老鼠的声音。",
    "A place that's always lit, no matter the time of the day": "一个无论一天中的什么时间都始终灯火通明的地方",
    "A very narrow and tight area where there's not much place for maneuvering": "非常狭窄和紧凑的区域，没有太多的操作空间",
    "Cave room": "洞穴房",
    "Go back to entrance": "返回入口处",
    "Go outside": "到外面去",
    "Go outside and to the village": "到外面去，到村里去",
    "Good, regular sleep is the basis of getting stronger and helps your body heal.": "良好、规律的睡觉是变得更强壮的基础，有助于身体康复。",
    "It's full of rats. At least the glowing mushrooms provide some light.": "里面全是老鼠。 至少发光的蘑菇提供了一些光线。",
    "Learn how to fight in narrow environment, where there's not much space for dodging attacks": "学习如何在狭窄的环境中战斗，那里没有太多的空间来躲避攻击",
    "Nearby cave": "附近的洞穴",
    "Shack": "窝棚",
    "Take a nap": "睡个午觉",
    "This small shack was the only spare building in the village. It's surprisingly tidy.": "这个小棚屋是村里唯一的闲置建筑。 出奇的整齐。",
    "Tight maneuvers": "紧密动作",
    "Unlocked location Nearby cave": "解锁地点 附近洞穴",
    "Unlocked location Shack": "解锁地点棚屋",
    "Wake up": "起床",
    "You still need to get stronger.": "你还需要变得更强。",
    "bright": "明亮",
    "narrow": "狭窄",
    "dagger": "匕首",
    "Saved the game manually": "手动保存了游戏",
    "Thanks to Spatial awareness reaching new milestone, Hero gained:": "由于空间感知达到了新的里程碑，英雄 获得了：",
    "Thanks to Persistence reaching new milestone, Hero gained:": "由于持久达到了新的里程碑，英雄 获得了：",
    "Pelt of a huge rat. Fur has terrible quality, but maybe leather could be used for something if you gather more?": "一只巨大老鼠的毛皮。 毛皮的质量很差，但如果你收集更多的话，也许皮革可以用来做点什么？",
    "Haggling": "讨价还价",
    "Lowers trader cost multiplier to 100% of original value": "将交易者成本乘数降低至原始价值的 100%",
    "Stop reading for now": "暂时停止阅读",
    "The art of the deal": "交易的艺术",
    "Ability to read and understand written text": "阅读和理解书面文字的能力",
    "Allows reading harder books": "允许阅读更难的书",
    "Cave depths": "洞穴深处",
    "Climb out": "爬出去",
    "A place where it's always as dark as during the night": "一个总是像夜晚一样漆黑的地方",
    "dark": "黑暗",
    "It's dark. And full of rats.": "这里很黑。并且充满了老鼠。",
    "Unlocked location Cave depths": "解锁地点：洞穴深处",
    "Chance to block an attack": "格挡攻击的几率",
    "Forest": "森林",
    "Forest surrounding the village, a dangerous place": "村庄周围的森林，是一个危险的地方",
    "Max!": "最大！",
    "Maxed out!": "满级了！",
    "Go back to Forest road": "返回森林小道",
    "Starving wolf": "饿狼",
    "Young wolf": "幼狼",
    "The ability to fight with the most deadly weapon in the history": "使用历史上最致命的武器进行战斗的能力",
    "A small, wild canine": "一只小型野生犬科动物",
    "A large, wild and hungry canine": "一只巨大的、野生的、饥饿的狗",
    "Ability to block attacks with shield": "能够用盾牌格挡攻击",
    "Finish patrolling": "完成巡逻",
    "Go on a patrol around the village.": "去村子周围巡逻。",
    "Leave the village": "离开村庄",
    "Move somewhere else": "去别的地方",
    "Return": "返回",
    "Talk to the village guard": "与村守卫交谈",
    "Starving wolf was defeated": "饿狼被击败了",
    "You are strong enough, you can leave and come whenever you want.": "当你足够强大时，你想走就走，想来就来。",
    "First and foremost, don't rush. It's fine to spend some more time here, to better prepare yourself. There's a lot of dangerous animals out there, much stronger than those damn rats, and in worst case you might even run into some bandits. If you see something that is too dangerous to fight, try to run away.": "首先也是最重要的一点，不要着急。 在这里多花点时间也好，让自己做好更好的准备。 那里有很多危险的动物，比那些该死的老鼠强大得多，最坏的情况下你甚至可能会遇到一些强盗。 如果你看到一些太危险而无法战斗的东西，请尝试逃跑。",
    "\"Can you give me any tips for the journey?\"": "“你能给我一些旅途建议吗？”",
    "Forest road": "森林小道",
    "Go for a run through the forest": "在森林里奔跑",
    "Leave the forest": "离开森林",
    "Leave the safe path": "离开安全道路",
    "Shabby road leading through a dark forest, the only way to leave the village": "破旧的道路穿过黑暗的森林，这是离开村庄的唯一途径",
    "Town outskirts": "城镇郊区",
    "You can see a tall stone wall, surrounded by a green open field.": "你可以看到一堵高高的石墙，周围是一片绿色的开阔田野。",
    "Young wolf was defeated": "幼狼被击败了",
    "\"Do you maybe have any jobs for me?\"": "“你们有工作给我吗?\”",
    "Hello. I see you are finally leaving, huh?": "你好。看来你终于要走了?",
    "Unlocked activity \"patrolling\" in location \"Village\"": "解锁活动“巡逻”在地点“村庄”",
    "You are somewhat combat capable now, so how about you help me and the boys on patrolling? Not much happens, but it pays better than working on fields": "你现在有点战斗能力了，所以你来帮我和孩子们巡逻怎么样?发生的事情不多，但比在地里干活挣钱多",
    "Ability to fight with use of axes": "使用斧头进行战斗的能力",
    "Ability to fight with use of battle hammers. Why bother trying to cut someone, when you can just crack all their bones?": "能够使用战锤进行战斗。 当你可以打断某人所有的骨头时，为什么还要费力去砍伤他们呢？",
    "The looked upon art of fighting (and stabbing) with daggers": "令人瞩目的用匕首战斗（和刺伤）的艺术",
    "Wolf fang": "狼牙",
    "Wolf pelt": "狼皮",
    "Your magic power. It affects the power of spells": "你的魔力。它影响法术的力量",
    "A normal and basic stance. It doesn't excell in anything, but also doesn't suffer any major flaws and is energy efficient.": "一个正常的和基本姿态。它没有任何优点，但也没有任何重大缺陷，而且很节能。",
    "Background": "背景",
    "Breakdown:": "分解:",
    "Fav": "收藏",
    "Focus your mind": "集中注意力",
    "Knowledge of all weapons": "所有武器的知识",
    "Magic": "魔法",
    "Name": "名称",
    "Normal Stance": "正常的姿态",
    "Normal stance": "正常的姿态",
    "Select": "选择",
    "Skills": "技能",
    "Stamina efficiency:": "耐力效率:",
    "Stances": "姿态",
    "An extremely dark place, darker than most of the nights": "一个极其黑暗的地方，比大多数夜晚都要黑暗",
    "As it gets damaged, your skin regenerates to be tougher and tougher": "当它受损时，你的皮肤会再生，变得越来越坚韧",
    "dark II": "黑暗 II",
    "Tough skin": "坚韧的皮肤",
    "Total price:": "总价格:",
    "Try to break the suspicious wall": "试着打破那堵可疑的墙",
    "A big cave near the village, once used as a storeroom. Groups of fluorescent mushrooms cover the walls, providing a dim light. Your efforts have secured a decent space and even a few tunnels, yet somehow you can still hear the sounds of the wolf rats.": "村子附近的一个大洞穴，曾经用作储藏室。一群群的荧光蘑菇覆盖着墙壁，提供昏暗的光线。你的努力确保了一个体面的空间，甚至一些隧道，但不知何故，你仍然可以听到狼鼠的声音。",
    "Train for a bit": "训练一会儿",
    "Medium-sized village built near a small river. It's surrounded by many fields, a few of them infested by huge rats which, while an annoyance, don't seem possible to fully eradicate. Other than that, there's nothing interesting around": "中等大小的村庄建在一条小河附近。它被许多田地包围着，其中一些被巨大的老鼠侵扰，虽然令人烦恼，但似乎不可能完全根除。除此之外，周围没有什么有趣的东西",
    "per every 2h  worked": "每工作2小时",
    "\"Do you have any work?\"": "“你有工作吗?”\”",
    "\"Hello, can I get in?\"": "“你好，我能进去吗?”\”",
    "\"Hello? Why are you looking at me like that?\"": "\“你好吗?你为什么那样看着我?\”",
    "\"Hello\"": "\“你好\”",
    "\"How are things around here?\"": "“这里的情况怎么样?”\”",
    "\"Twist liek a snek\"": "“扭得像条蛇”",
    "A wild settlement next to city walls, filled with decaying buildings and criminals": "城墙旁的荒蛮之地，到处都是腐朽的建筑和罪犯",
    "Defend yourself!": "保护你自己!",
    "Fight off the assailant": "击退攻击者",
    "Fight off the suspicious man": "击退那个可疑的人",
    "He attacked you out of nowhere": "他莫名其妙地袭击了你",
    "Hello stranger": "你好陌生人",
    "Nothing to complain about. Trouble is rare, pay is good, and the soil is as fertile as my wife!": "没什么可抱怨的。麻烦少，报酬好，土壤像我老婆一样肥沃!",
    "Old trodden road leading through a dark forest, the only path connecting village to the town. You can hear some animals from the surrounding woods.": "一条被踩过的老路穿过一片漆黑的森林，这是连接村庄和城镇的唯一道路。你可以听到周围树林里传来的动物叫声。",
    "Return to the forest": "回到森林",
    "Run away for now": "暂时逃跑吧",
    "Semi-private farms under jurisdiction of the city council. Full of life and sounds of heavy work.": "市议会管辖下的半私人农场。充满生机和繁重工作的声音。",
    "Slums": "贫民窟",
    "Suspicious man": "可疑的男人",
    "Talk to the farm supervisor": "和农场主管谈谈",
    "Talk to the gate guard": "和门卫谈谈",
    "Talk to the suspicious man": "和那个可疑的人谈谈",
    "The town is currently closed to everyone who isn't a citizen or a guild member. No exceptions.": "这个小镇目前对所有不是市民或公会成员的人关闭。没有例外。",
    "The town is surrounded by a tall stone wall. The only gate seems to be closed, with a lone guard outside. You can see farms to the north and slums to the south.": "这座城镇被一堵高高的石墙包围着。唯一的大门似乎是关着的，外面只有一个卫兵。你可以看到北边是农场，南边是贫民窟。",
    "This book has a terrible grammar, seemingly written by some uneducated bandit, but despite that it quite well details how to properly evade attacks.": "这本书有一个可怕的语法，似乎是由一些没有受过教育的土匪写的，但尽管如此，它相当详细地说明了如何正确地逃避攻击。",
    "Town farms": "城镇农场",
    "Trade with suspicious trader": "与可疑商人交易",
    "Twist liek a snek": "像一只鞋一样扭动",
    "Unlocked activity \"fieldwork\" in location \"Town farms\"": "解锁活动\“耕作\”在位置\“城镇农场\”",
    "We sure could use more hands. Feel free to help my boys on the fields whenever you have time!": "我们确实需要人手。只要你有时间，随时可以在球场上帮助我的孩子们!",
    "Y-you! You should be dead! *the man pulls out a dagger*": "你!你应该死了!男人掏出一把匕首",
    "Finish meditating": "完成冥想",
    "Finish fieldwork": "完成耕作",
    "patrolling": "巡逻",
    "running": "跑步",
    "Sit down and meditate": "坐下来冥想",
    "meditating": "冥想",
    "\"*You almost tripped on some roots*\"": "“*你差点被树根绊倒*\”",
    "\"*You hear some animal running away*\"": "“*你听到有动物跑开了*”",
    "\"*You hear some rustling*\"": "“你听到沙沙声了吗?”",
    "\"Roar!\"": "\“吼!\”",
    "Broad Arc": "宽弧",
    "Crushing Force": "粉碎之力",
    "dark III": "黑暗 III",
    "Quick Steps": "快步走",
    "Stance mastery": "姿态精通",
    "A big cave near the village, once used as a storeroom. Groups of fluorescent mushrooms cover the walls, providing a dim light. Your efforts have secured a decent space and many of the tunnels. It seems like you almost reached the deepest part.": "村子附近的一个大洞穴，曾经用作储藏室。一群群的荧光蘑菇覆盖着墙壁，提供昏暗的光线。你的努力确保了一个合适的空间和许多隧道。看起来你快要到达最深的部分了。",
    "\"I found an even deeper tunnel in the cave\"": "“我在洞里发现了一条更深的隧道。”",
    "1 finished fieldwork": "完成 1 实地考察",
    "A large, wild canine": "一种大型的野狗",
    "A powerful and dangerous technique that abandons speed in favor of overwhelmingly strong attacks": "这是一种强大而危险的技术，它放弃了速度，转而支持压倒性的强大攻击",
    "A special technique that allows striking multiple enemies at once, although at a cost of lower damage": "这是一种特殊的技能，可以同时攻击多个敌人，但造成的伤害较低",
    "A swift and precise technique that abandons strength in favor of greater speed": "一种迅速而精确的技术，放弃力量而追求更快的速度",
    "Ability to sense a presence without using your eyes": "不用眼睛就能感觉到存在的能力",
    "Elite wolf rat": "精英狼鼠",
    "hidden tunnel": "隐藏隧道",
    "Cave depths": "洞穴深处",
    "Cave room": "洞穴房间",
    "Infested field": "被感染的田野",
    "Fang of a wild wolf. Somewhat sharp, still not very useful. Maybe if it had a bit better quality...": "野狼的獠牙。有点尖锐，但仍然不是很有用。如果它的质量好一点的话……",
    "Go into the pitch black tunnel": "进入漆黑的隧道",
    "Hidden tunnel": "隐藏的隧道",
    "High quality wolf fang": "高品质狼牙",
    "Hits up to 5 enemies": "最多击中5个敌人",
    "Improves efficiency of the 'Quick Steps' stance": "提高“快速步”姿势的效率",
    "Improves efficiency of the \"Broad arc\" stance": "提高“宽弧”姿态的效率",
    "Improves efficiency of the \"Crushing force\" stance": "提高“粉碎力”姿态的效率",
    "Increases xp gains of all combat stance skills of level lower than this, x1.1 per level of difference": "增加低于此等级的所有战斗姿态技能的经验值，每等级增加x1.1",
    "It's definitely, unquestionably, undoubtedly better to just use a weapon instead of doing this. But sure, why not?": "毫无疑问，使用武器比这样做要好得多。当然，为什么不呢?",
    "Knowledge on how to apply different stances in combat": "了解如何在战斗中运用不同的姿势",
    "Multiplies damage dealt in unarmed combat by 2.144. \nMultiplies attack speed in unarmed combat by 1.464": "徒手格斗的伤害增加2.144。徒手格斗的攻击速度提高1.464",
    "Pelt of a wild wolf. It's a bit damaged so it won't fetch a great price, but the leather itself could be useful.": "野狼的毛皮。有点损坏，所以卖不出好价钱，但皮革本身可能有用。",
    "Pitch black tunnel": "漆黑的隧道",
    "Pure darkness with not even a tiniest flicker of light": "一片漆黑，没有一丝微光",
    "Rat with size of a dog, much more ferocious than its relatives": "老鼠和狗一样大，比它的亲戚凶猛得多",
    "Retreat for now": "暂时撤退",
    "The what?... I have a bad feeling about this, you better avoid it until you get better equipment. Don't forget to bring a good shield too.": "什么?…我有一种不好的预感，在你有更好的设备之前，你最好避开它。别忘了带上一个好的盾牌。",
    "There is no light here. Only rats.": "这里没有光。只老鼠。",
    "There is, in fact, even more rats here.": "事实上，这里有更多的老鼠。",
    "Venture deeper into the woods": "冒险深入森林",
    "Deep forest": "森林深处",
    "Deeper part of the forest, a dangerous place": "森林深处，一个危险的地方",
    "\"Mooooo!\"": "\"嗷呜!\"",
    "Alchemy": "炼金",
    "Activity skills": "可用技能",
    "A nice leather hat to protect your head.": "一顶漂亮的皮帽，可以保护你的头。",
    "Cooking": "烹饪",
    "Combat skills": "战斗技能",
    "Boar trophy": "野猪战利品",
    "Crafting": "制作",
    "Create": "制造",
    "Dagger": "匕首",
    "Forging": "锻造",
    "Glove exterior": "手套外观",
    "Gloves": "手套",
    "Hammer": "锤",
    "Don't autoswitch out from inventory when starting combat": "不要在开始战斗时自动退出背包",
    "Dozens of tiny iron rings linked together. Nowhere near a wearable form, turning it into armor will still take a lot of effort and focus": "几十个小铁环连在一起。它离可穿戴的形式还很远，把它变成盔甲仍然需要付出很多努力和精力",
    "Cheapest form of wood, ready to be used. Despite being rather weak, it still has a lot of uses.": "最便宜的木材，随时可以使用。尽管很弱，但它仍然有很多用途。",
    "Character skills": "角色技能",
    "Big piece of an old bread, still edible.": "一大块旧面包，还能吃。",
    "Comfortable leather vest, offering a low protection.": "舒适的皮革背心,提供较低的保护。",
    "Sword": "剑",
    "Your artifact slot": "你的神器槽",
    "Your axe slot": "你的斧子槽",
    "Your pickaxe  slot": "你的镐子槽",
    "Your sickle  slot": "你的镰刀槽",
    "Wolf trophy": "狼奖杯",
    "Weapon skills": "武器技能",
    "Wool cloth": "羊毛布",
    "Try lifting some of the rocks": "试着举起一些石头",
    "Thick and warm, might possibly absord some punches": "又厚又暖和，可能会吸收一些击打",
    "Thick and resistant leather, too stiff for clothes but perfect for armor": "Thick and resistant leather, too stiff for clothes but perfect for armor",
    "Tastes kinda nice and provides a quick burst of healing": "味道还不错，能让你很快恢复生命值",
    "Tail of a huge rat. Doesn't seem very useful, but maybe some meat could be recovered from it": "一只大老鼠的尾巴。看起来没什么用，但也许可以从中提取一些肉",
    "Items/trinkets": "物品/饰品",
    "Leg armor": "腿甲",
    "Leg armor exterior": "腿甲外观",
    "LOADING": "加载中",
    "Levels / unlocks": "等级 / 解锁",
    "Long blade": "长刀",
    "Long shaft": "长杆",
    "Oneberry juice": "一莓果汁",
    "Low quality iron ingot": "劣质铁锭",
    "Pants": "裤子",
    "Processed rough wood": "加工粗糙的木头",
    "Result:": "结果:",
    "Roasted rat meat": "烤鼠肉",
    "Roasted purified rat meat": "烤纯鼠肉",
    "Select one component from each category": "从每个类别中选择一个组件",
    "Hat": "帽子",
    "Inventory": "背包",
    "ingot": "铸锭",
    "It doesn't suffer from any excessive impurities and can be used without worries.": "不受任何杂质超标的影响，可以放心使用。",
    "It has a lot of impurities, resulting in it being noticeably below the market standard": "它有很多杂质，导致明显低于市场标准",
    "It's slightly damaged and seems useless for anything that requires precise work.": "它有点损坏，似乎对任何需要精确工作的东西都没用。",
    "Items": "物品",
    "Materials required:": "材料要求:",
    "Piece of wolf rat leather": "一块狼鼠皮",
    "Piece of wolf leather": "一张狼皮",
    "Piece of boar leather": "一块野猪皮",
    "Rat meat chunks": "老鼠肉块",
    "Shield": "盾牌",
    "Shield base": "盾牌基础",
    "Shield handle": "盾牌短柄",
    "Shoes": "鞋子",
    "Shirt": "衬衫",
    "Shoes exterior": "鞋子外观",
    "Short blade": "短刀",
    "Short hilt": "短柄",
    "sickle slot": "镰刀槽",
    "sickle": "镰刀",
    "Spear": "矛",
    "[Cave depths]": "[洞穴深处]",
    "[Cave room]": "[洞穴房间]",
    "Environmental skills": "环境技能",
    "Effects:": "效果:",
    "Gauntlets": "长手套",
    "Helmet": "头盔",
    "Hammer head": "锤子头",
    "Helmet exterior": "头盔外观",
    "Basic meal' :": "基本餐' :",
    "Weak healing powder' :": "弱愈合粉'：",
    "Weak healing potion' :": "弱治疗药水'：",
    "Slight food poisoning' :": "轻微食物中毒'：",
    "Average quality wood, ready to be used.": "中等质量的木材，随时可以使用。",
    "artifact slot": "神器槽",
    "Axe": "斧子",
    "Axe head": "斧子头",
    "axe slot": "斧子槽",
    "BGM": "背景音乐",
    "chainmail": "链甲",
    "Chestplate": "胸板甲",
    "Chestplate exterior": "胸板甲外观",
    "Components": "组件",
    "Increase size of text in dialogues": "增加对话框中的文本大小",
    "Medium handle": "中型把柄",
    "Not very potent, but can still make body heal noticeably faster for quite a while": "不是很有效，但仍然可以使身体愈合明显更快一段时间",
    "pickaxe slot": "镐子槽",
    "Processed wood": "加工过的木头",
    "Smelting": "冶炼",
    "Smell might be fine now, but it still seems like a bad idea to eat it": "现在闻起来可能没问题，但吃它似乎还是个坏主意",
    "Smells alright and should be safe to eat, yet you still have some doubts": "闻起来还不错，应该可以安全食用，但你还是有些疑虑",
    "Solid leather pants.": "结实的皮裤。",
    "Somewhat strong, should offer some protection when turned into armor": "有些坚固，当变成盔甲时应该能提供一些保护",
    "Stance skills": "姿态技能",
    "Success chance:": "成功率:",
    "Your pickaxe slot": "你的镐子槽",
    "Your sickle slot": "你的镰刀槽",
    "artifact": "神器",
    "Eww": "Yue",
    "'Basic meal' :": "'基本餐' :",
    "'Cheap meat meal' :": "'廉价的肉餐' :",
    "'Slight food poisoning' :": "'轻微食物中毒' :",
    "'Weak healing potion' :": "'弱治疗药水' :",
    "'Weak healing powder' :": "'弱治疗药粉' :",
    "Armored shoes": "铠甲鞋",
    "\"*You hear rocks rumbling somewhere*\"": "“*你听到石头在某处隆隆作响*”",
    "\"Squeak!\"": "\“吱吱声!\”",
    "Try to keep your balance on rocks in the river": "在河中的岩石上尽量保持平衡",
    "per every 2h worked": "每工作2小时",
    "Medium-sized village, built next to a small river at the foot of the mountains. It's surrounded by many fields, a few of them infested by huge rats, which, while an annoyance, don't seem possible to fully eradicate. Other than that, there's nothing interesting around": "一个中等大小的村庄，建在山脚下一条小河的旁边。它被许多田地包围着，其中一些被巨大的老鼠侵扰，虽然令人烦恼，但似乎不可能完全根除。除此之外，周围没有什么有趣的东西",
    "You can now talk with old craftsman": "你现在可以和老工匠交谈了",
    "You have gained the ability to craft items and equipment!": "你已经获得了制造物品和装备的能力！",
    "You have gained the ability to gather new materials!": "你已经获得了收集新材料的能力！",
    "Woodcutting": "伐木",
    "Try to craft something": "尝试制作一些东西",
    "Talk to the old craftsman": "与老工匠对话",
    "Talk to someone": "和某人交谈",
    "Piece of rough wood": "一块粗糙的木头",
    "Old sickle": "旧镰刀",
    "Old pickaxe": "旧镐子",
    "\"?????\" skill lvl 0 to 10": "\"?????\" 技能等级 0 到 10",
    "\"Could you remind me how to create equipment for myself?\"": "“你能提醒我如何为自己制作装备吗？”",
    "\"Could you remind me how to get crafting materials?\"": "“你能提醒我如何获得制作材料吗？”",
    "\"Could you remind me how to improve my creations?\"": "“你能提醒我如何改进我的创作吗？”",
    "\"Hello, I heard you wanted to talk to me?\"": "“你好，我听说你想和我谈谈？”",
    "\"I'm not interested.\"": "“我不感兴趣。”",
    "\"Sure, I'm in no hurry.\"": "“当然，我不着急。”",
    "\"Woodcutting\" skill lvl 0 to 10": "\"伐木\" 技能等级 0 到 10",
    "*[Old man spends some time explaining all the important basics of crafting and providing you with tips]*": "*[老男人花了一些时间解释所有重要的基本工艺，并提供给你提示]*",
    "1 obtained \"Old axe\"": "1 获得的\“旧斧头\”",
    "1 obtained \"Old pickaxe\"": "1 获得的\“旧镐子\”",
    "1 obtained \"Old sickle\"": "1 获得的\“旧镰刀\”",
    "An old axe that has seen better times, but is still usable": "一把经历过好日子的旧斧头，但仍然可用",
    "An old pickaxe that has seen better times, but is still usable": "一把旧镐子，虽历经沧桑，但仍可使用",
    "And old herb sickle that has seen better time, but is still usable": "还有旧的药草镰刀，虽然见过更好的时间，但仍然可用",
    "Cheapest form of wood. There's a lot of bark and malformed pieces.": "最便宜的木材。有很多树皮和畸形的碎片。",
    "Efficiency scaling:": "效率比例:",
    "Finish woodcutting": "完成伐木",
    "Gather some wood on the outskirts": "到郊外去收集一些木头",
    "Get better with chopping the wood": "把砍木头做得更好",
    "Old axe": "旧斧子",
    "Crafting skills": "制作技能",
    "Failed to create Piece of wolf rat leather!": "狼鼠皮制作失败！",
    "The art of preparing different elements and assembling them together": "把不同的元素准备好并组合在一起的艺术",
    "Ahh, of course. Unless you are talking about something simple like basic clothing, then you will first need to create components that can then be assembled together. For weapons, you generally need a part that you use to hit an enemy and a part that you hold in your hand. For armor, you will need some actual armor and then something softer to wear underneath, which would mostly mean some clothes.": "啊，当然。除非你是在谈论一些简单的东西，比如基本的衣服，否则你首先需要创建可以组装在一起的组件。对于武器，你通常需要一个用来打击敌人的部件和一个握在手里的部件。至于盔甲，你需要一些真正的盔甲，然后里面穿一些更柔软的东西，这主要意味着一些衣服。",
    "Ahh, that's simple, you just need more experience. This alone will be a great boon to your efforts. For equipment, you might also want to start with better components. After all, even with the most perfect assembling you can't turn a bent blade into a legendary sword.": "啊，这很简单，你只是需要更多的经验。仅此一点就会对你的努力大有裨益。对于设备，您可能还需要从更好的组件开始。毕竟，即使是最完美的组装，你也不能把一把弯曲的刀刃变成一把传说中的剑。",
    "Ahh, there's multiple ways of that. You can gain them from fallen foes, you can gather them around, or you can even buy them if you have some spare coin.": "啊，有很多种方法。你可以从倒下的敌人那里获得它们，你可以收集它们，或者如果你有多余的硬币，你甚至可以购买它们。",
    "pants made from cheapest resources available.": "裤由最便宜的资源制成的。",
    "A cheap leather hat to protect your head.": "一顶廉价的皮帽来保护你的头。",
    "Freshly baked bread, delicious.": "新鲜出炉的面包，好吃极了。",
    "Glass phial": "玻璃小瓶",
    "leather hat": "皮帽",
    "Small glass phial, a perfect container for a potion": "小玻璃瓶，装药水的绝佳容器",
    "Vest providing very low protection. Better not to know what's it made from": "背心提供非常低的保护。最好不要知道是什么做的",
    "helmet": "头盔",
    "Slums": "贫民窟",
    "Town farms": "城镇农场",
    "Town outskirts": "城郊",
    "Forest road": "森林小道",
    "Village": "村庄",
    "Nearby cave": "附近的洞穴",
    "Shack": "小屋",
    "Go towards the town": "前往城镇",
    "Equilibrium": "平衡",
    "Finish balancing": "完成平衡",
    "Nothing will throw you off your balance (at least the physical one)": "没有什么能让你失去平衡（至少是身体上的平衡）",
    "A completely open area where attacks can come from any direction": "一个完全开放的区域，攻击可以来自任何方向",
    "chainmail armor": "链甲护甲",
    "chainmail helmet": "链甲头盔",
    "chainmail pants": "链甲裤子",
    "Crude iron shield": "粗铁护盾",
    "armor": "铠甲",
    "armored pants": "铠装裤子",
    "\"Are you behaving yourself?\"": "“你表现好吗？”",
    "Y-yes! Please don't beat me again!": "对、对！请不要再打我了！",
    "\"Do you have any task that requires some good old violence?\"": "“你有什么任务需要一些古老的暴力吗？",
    "\"Do you sell anything?\"": "“你卖什么东西吗？”\”",
    "I kinda do, but you don't seem strong enough for that. I'm sorry.": "我有点想，但你似乎不够强大。我很抱歉。",
    "Sorry, I'm not allowed to. I could however let you take some stuff in exchange for physical work, and it just so happens our sheep need shearing.": "对不起，我不能这么做。不过，我可以让你拿些东西来换取体力劳动，碰巧我们的羊需要剪羊毛。",
    "Take care of local sheep in exchange for some wool": "照顾当地的羊，以换取一些羊毛",
    "Unlocked activity \"animal care\" in location \"Town farms\"": "解锁活动\“动物护理\”地点\“城镇农场\”",
    "Finish animal care": "完成动物护理",
    "Knowledge and skills required to deal with a wide variety of animals": "与各种各样的动物打交道所需的知识和技能",
    "\"*You can hear snoring workers*\"": "“*你可以听到工人的鼾声*”",
    "\"*You can hear some rustling*\"": "”*你可以听到一些沙沙声*”",
    "\"*You notice a goat staring at you menacingly*\"": "“*你注意到一只山羊正威胁地盯着你*”",
    "\"Animal handling\" skill lvl 0 to 10": "“动物处理”技能等级 0 - 10",
    "\"Mining\" skill lvl 0 to 10": "“采矿”技能等级 0 到 10",
    "\"Bark bark!\"": "“汪汪汪汪！”",
    "\"Cock-a-doodle-doo!\"": "“喔——喔——喔！”",
    "\"Look, a bird!\"": "“看，一只鸟！”",
    "\"Neigh!\"": "“马嘶声!”",
    "\"Oink oink\"": "“哼哼”",
    "A handful of wool, raw and unprocessed": "一把未加工的羊毛",
    "Animal handling": "动物处理",
    "Wool": "羊毛",
    "gloves": "手套",
    "shoes": "鞋子",
    "Solid shoes made of leather, a must have for any traveler": "结实的皮制鞋子，旅行必备",
    "Strong leather gloves, perfect for handling rough and sharp objects.": "结实的皮革手套，非常适合处理粗糙和尖锐的物品。",
    "\"Please, do you have a coin to spare?\"": "“拜托，你有多余的硬币吗？”",
    "Turning raw metal into something useful": "把未经加工的金属变成有用的东西",
    "Thick hide of a wild boar. Too stiff for clothing, but might be useful for an armor": "野猪的厚皮。太硬了，不能做衣服，但可以做盔甲",
    "Tusk of a wild boar. Sharp and long enough to easily kill an adult human": "野猪的獠牙。又锋利又长，足以轻易杀死一个成年人",
    "A large wild creature, with thick skin and large tusks": "一种大型野生动物，有厚皮和大獠牙",
    "Small, round, dark-green leaves with with very good disinfectant properties": "叶子小而圆，深绿色，具有很好的消毒性能",
    "Small blue berries capable of stimulating body's natural healing": "能刺激身体自然愈合的蓝色小浆果",
    "Pieces of boar leather shaped for gloves.": "做成手套的野猪皮。",
    "Piece of wood": "木片",
    "ore": "矿石",
    "Oneberry": "一莓",
    "Mutated and dark bone of a monster. While far on the weaker side, it's still very strong": "变异的怪物黑骨。虽然处于较弱的一面，但它仍然非常强大",
    "Making the unedible edible": "把不能吃的变成可以吃的",
    "Low quality iron ore": "低品质铁矿石",
    "Knowledge of useful plants and mushrooms": "关于有用植物和蘑菇的知识",
    "It's no longer dog-sized, but rather around the size of an average wolf, with thicker skin, longer claws and pure insanity in the eyes": "它不再是狗的大小，而是一只普通狼的大小，皮肤更厚，爪子更长，眼睛里充满了疯狂",
    "Average quality wood. There's a lot of bark and malformed pieces.": "质量一般的木材。有很多树皮和畸形的碎片。",
    "Basic stats:": "基本数据:",
    "Belmart leaf": "贝尔玛特叶子",
    "Big green-brown leaves that can be applied to wounds to speed up their healing": "大的绿棕色叶子，可以涂在伤口上，加速伤口愈合",
    "Boar": "野猪",
    "Boar hide": "野猪皮",
    "glove armor": "手套护甲",
    "Boar meat": "野猪肉",
    "content is rather low and there are a lot of problematic components that can't be fully removed, which will affect created materials.": "内容相当低，有很多有问题的组件不能完全删除，这将影响创建的材料。",
    "Elite wolf rat guardian": "精英狼鼠守护者",
    "Extracting and enhancing useful properties of the ingredies": "提取和提高成分的有用性质",
    "Fang of a wild wolf. Very sharp, undamaged and surprisingly clean.": "野狼的獠牙。非常锋利，完好无损，非常干净。",
    "Fatty meat of a wild boar, all it needs is to be cooked.": "野猪的肥肉，只需要煮熟就可以了。",
    "Get better with mining the ores": "在开采矿石方面做得更好",
    "Golmoon leaf": "魔门叶",
    "High quality boar tusk": "高品质的野猪牙",
    "Hits up to 6 enemies": "最多攻击6个敌人",
    "It has a decent iron content and can be smelt into market-quality iron.": "它的铁含量不错，可以冶炼成市场上的铁。",
    "Weak monster bone": "弱怪骨",
    "Turning raw ore into raw metal": "将原始矿石变成原始金属",
    "cuirass": "胸甲",
    "greaves": "护膝",
    "helmet armor": "头盔护甲",
    "shoe armor": "脚部护甲",
    "Wool gloves": "羊毛手套",
    "Wool hat": "羊毛帽",
    "Wool shirt": "羊毛衬衫",
    "check": "检查",
    "\"Tomorrow I'm gonna fix the roof\"": "“明天我要修屋顶。”",
    "A decent wooden handle for holding the shield": "一个用来拿盾牌的木柄",
    "A long shaft for a spear, somewhat uneven": "矛柄长矛的长柄，有点不均匀",
    "A medium handle for an axe or a hammer": "斧柄：用于斧头或锤子的中等柄",
    "A shield base of rather bad quality, but at least it won't fall apart by itself": "一个质量相当差的盾牌底座，但至少它不会自己裂开",
    "A short handle for a sword or maybe a dagger": "剑或匕首的短柄",
    "A simple handle for holding the shield": "握盾的简单把手",
    "Failed to create Piece of boar leather!": "没能造出一块野猪皮！",
    "Failed to create Wool cloth!": "创建羊毛布料失败！",
    "Greaves made of thick boar leather. Just attach them onto some pants and you are ready to go.": "格里夫是用厚厚的公猪皮革制成的。只要把它们贴在裤子上，就可以了。",
    "Greaves made of wolf leather. Just attach them onto some pants and you are ready to go.": "格里夫是用狼皮做的。只要把它们贴在裤子上，就可以了。",
    "It's thick enough to weaken a blow, but you shouldn't hope for much. On the plus side, it's light and doesn't block your moves.": "它很厚，足以减弱一击，但你不应该抱太大希望。有利的一面是，它很轻，不会阻碍你的行动。",
    "leather shoes": "皮鞋",
    "Long wooden shaft": "长木杆",
    "Material required:": "材料要求:",
    "Medium wooden handle": "中木柄",
    "Pieces of boar leather shaped for shoes.": "做鞋用的野猪皮。",
    "Pieces of wolf leather shaped for gloves.": "做手套用的狼皮。",
    "Pieces of wolf leather shaped for shoes.": "做鞋用的狼皮。",
    "Proper wooden shield base, although it could use some additional reinforcement": "适当的木质护盾底座，虽然还需要一些额外的加固",
    "shield base": "护盾底座",
    "shield handle": "盾柄",
    "Shoes made of thin and cheap leather. Even then, they are in every single aspect better than not having any.": "用薄而廉价的皮革制成的鞋。即便如此，他们在各个方面都比没有好。",
    "Short wooden hilt": "短木柄",
    "Simple cuirass made of solid wolf leather, all it needs now is something softer to wear under it.": "简单的铁甲是用狼皮做的，现在只需要在里面穿件更柔软的东西。",
    "Simple long wooden shaft": "简易长木轴",
    "Simple medium wooden handle": "简易中号木柄",
    "Simple short wooden hilt": "简单的短木柄",
    "Simple woollen hat to protect your head.": "简单的羊毛帽子，保护你的头。",
    "Strenghtened wolf leather, ready to be used as a part of a helmet": "强化的狼皮，准备用作头盔的一部分",
    "String cuirass made of boar leather.": "用公猪皮革制成的细绳铁甲。",
    "Strong boar leather, ready to be used as a part of a helmet": "坚固的野猪皮革，准备用作头盔的一部分",
    "Warm and comfy, but they don't provide much protection.": "温暖舒适，但它们不能提供太多保护。",
    "the mysterious gate": "秘之门",
    "Finish mining": "完成采矿",
    "Elite wolf rat was defeated": "精英狼鼠被击败了",
    "Mine some of the deeper iron vein": "开采一些更深的铁矿脉",
    "Mine the strange looking iron vein": "开采那奇怪的铁矿脉",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "[Cheap long iron blade]": "[廉价的长铁刀]",
    "[living] [beast] [wolf rat] [monster] [medium]": "[活的][野兽][狼鼠][怪物][中等]",
    "[Short wooden hilt]": "[短木柄]",
    "[Comp]": "[对比]",
    "[feet]": "[脚部]",
    "[arms]": "[手部]",
    "[Crude iron shield base]": "[粗铁盾牌底座]",
    "[Iron chainmail greaves]": "[铁锁子甲护膝]",
    "[Iron chainmail helmet armor]": "[铁锁子甲头盔]",
    "[Iron chainmail vest]": "[铁锁子甲背心]",
    "[Iron shield base]": "[铁盾底座]",
    "[Leather vest]": "[皮背心]",
    "[Leather pants]": "[皮裤]",
    "[Wolf leather cuirass]": "[狼皮铠甲]",
    "[Wolf leather greaves]": "[狼皮护膝]",
    "[Wooden shield handle]": "[木盾把柄]",
    "[Slums]": "[贫民窟]",
    "[Town farms]": "[城镇农场]",
    "[Town outskirts]": "[城郊]",
    "[Forest road]": "[森林小道]",
    "[Deep forest]": "[森林深处]",
    "[Village]": "[村庄]",
    "[Shack]": "[小屋]",
    "[Nearby cave]": "[附近的洞穴]",
    "[Crude wooden shield base]": "[粗糙的木盾底座]",
    "[Cheap wooden shield base]": "[便宜的木盾底座]",
    "[Cheap short iron blade]": "[便宜的铁短刀]",
    "[Cheap iron hammer head]": "[便宜的铁锤子头]",
    "[Cheap iron axe head]": "[便宜的铁斧子头]",
    "[Wolf leather helmet armor]": "[狼皮头盔护甲]",
    "[Leather hat]": "[皮帽]",
    "[tool]": "[工具]",
    "[Simple medium wooden handle]": "[简单的中等木柄]",
    "[Simple short wooden hilt]": "[简单的短木柄]",
    "[Wooden shield base]": "[木盾底座]",
    "[Simple long wooden shaft]": "[简单的长木杆]",
    "[shield handle]": "[盾牌把柄]",
    "[medium handle]": "[中型把柄]",
    "[long handle]": "[长柄]",
    "[Long iron blade]": "[铁长刀]",
    "[Short iron blade]": "[铁短刀]",
    "[short blade]": "[短刀]",
    "[long blade]": "[长刀]",
    "[living] [beast] [medium]": "[活着] [野兽] [中型]",
    "[living] [beast] [small]": "[活着] [野兽] [小型]",
    "[living] [beast] [wolf rat] [pest] [small]": "[活着] [野兽] [狼鼠] [害虫] [小型]",
    "[leg armor interior]": "[腿甲内饰]",
    "[shoes interior]": "[鞋子内饰]",
    "[glove interior]": "[手套内饰]",
    "[Crude wooden shield handle]": "[粗木盾牌柄]",
    "[helmet interior]": "[头盔内饰]",
    "[chestplate interior]": "[胸板内饰]",
    "[leg armor exterior]": "[腿甲外观]",
    "[shoes exterior]": "[鞋子外观]",
    "[helmet exterior]": "[头盔外观]",
    "[glove exterior]": "[手套外观]",
    "[chestplate exterior]": "[板胸外观]",
    "[hammer head]": "[锤子头]",
    "[Iron hammer head]": "[铁锤子头]",
    "[Iron axe head]": "[铁斧子头]",
    "[axe head]": "[斧子头]",
    "[short handle]": "[短柄]",
    "[shield base]": "[盾牌基础]",
    "[ Entering Hidden tunnel ]": "[进入隐蔽隧道]",
    "[ Entering Pitch black tunnel ]": "[进入漆黑的隧道]",
    "[Pitch black tunnel]": "[漆黑的隧道]",
    "[ Entering Deep forest ]": "[ 进入森林深处 ]",
    "[Hidden tunnel]": "[隐藏隧道]",
    "[head]": "[头部]",
    "[ Entering Fight off the assailant ]": "[进入并击退攻击者]",
    "[ Entering Slums ]": "[进入贫民窟]",
    "[ Entering Town farms ]": "[进入城镇农场]",
    "[ Entering Forest road ]": "[ 进入森林小道 ]",
    "[ Entering Town outskirts ]": "[ 进入城镇郊区 ]",
    "[Forest]": "[森林]",
    "[ Entering Forest ]": "[ 进入森林 ]",
    "[ Entering Cave depths ]": "[ 进入洞穴深处 ]",
    "[read]": "[阅读]",
    "[Cave depths]": "[洞穴深处]",
    "[ Entering Cave room ]": "[进入洞室]",
    "[ Entering Nearby cave ]": "[进入附近的洞穴]",
    "[ Entering Shack ]": "[进入小屋]",
    "[Cave room]": "[洞穴室]",
    "[Infested field]": "[被感染的田野]",
    "[Shack]": "[窝棚]",
    "[equip]": "[装备]",
    "[ Entering Village ]": "[ 进入村庄 ]",
    "[ Entering Infested field ]": "[ 进入被感染的田野 ]",
    "[off-hand]": "[副手]",
    "[torso]": "[躯干]",
    "[shield]": "[盾牌]",
    "[Book]": "[书籍]",
    "[weapon]": "[武器]",
    "[use]": "[使用]",
    "[legs]": "[腿部]",
    "[take off]": "[卸下]",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "v0.3.5i": "v0.3.5i",
    "v0.4.0o": "v0.4.0o",
    "pickaxe": "pickaxe",
    "keyboard_double_arrow_down": "keyboard_double_arrow_down",
    "nightlight_round": "nightlight_round",
    "light_mode": "light_mode",
    "format_list_bulleted": "format_list_bulleted",
    "bed": "bed",
    "directions": "directions",
    "construction": "construction",
    "storefront": "storefront",
    "fitness_center": "fitness_center",
    "warning_amber": "warning_amber",
    "arrow_back": "arrow_back",
    "question_answer": "question_answer",
    "help_outline": "help_outline",
    "work_outline": "work_outline",
    "search": "search",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n                                    ": "\n                                    ",
    "\n                                ": "\n                                ",
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\n\n": "\n\n",
    "\n": "\n",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Night vision : level ": "夜视：等级 ",
    "Quality: ": "质量：",
    "Crit rate +": "暴击率 +",
    "Cheap ": "便宜的",
    "wooden ": "木",
    "Wooden ": "木",
    "iron ": "铁",
    "Iron ": "铁",
    "Leather ": "皮",
    "Crude wooden ": "粗木",
    "Atk pwr: ": "攻击力：",
    "Atk spd:": "攻速：",
    "Attack speed x": "攻速 x",
    "\n": "\n",
    "EP:": "闪避：",
    "Carring heavy things": "搬运重物",
    "Just running around": "只是到处乱跑",
    "Agility +": "敏捷 +",
    "Hit: ": "命中：",
    "Weapon mastery : level ": "武器精通：等级 ",
    "Unlocked new skill: ": "解锁新技能：",
    "Ddg: ": "Ddg: ",
    "Pest killer : level ": "害虫杀手：等级 ",
    "Base xp value: ": "基础经验值：",
    "Combat : level ": "战斗：等级 ",
    "Spatial awareness : level ": "空间感知：等级 ",
    "Swordsmanship : level ": "剑术：等级 ",
    "Multiplies damage dealt with swords by ": "剑造成的伤害乘以 ",
    "Multiplies damage dealt with axes by ": "斧子造成的伤害乘以 ",
    "Multiplies damage dealt with daggers by ": "匕首造成的伤害乘以 ",
    "Multiplies damage dealt with battle hammers by ": "战锤造成的伤害乘以 ",
    "Multiplies hit chance against small-type enemies by ": "对小型敌人的命中率提高 ",
    "Multiplies hit chance by ": "命中率乘以 ",
    "Multiplies strength by ": "力量乘以 ",
    "Parent skill: ": "家长技能：",
    "Multiplies max stamina by ": "最大耐力乘以 ",
    "Running : level ": "跑步 : 等级 ",
    "Weightlifting has reached level ": "举重达到等级 ",
    "Swordsmanship has reached level ": "剑术达到等级 ",
    "Running has reached level ": "跑步达到等级 ",
    "Working on the fields": "田间劳作",
    "(earnings: ": "(获得了: ",
    "Farming : level ": "耕作 : 等级",
    "Hero earned ": "英雄赚取了 ",
    "Weightlifting : level ": "举重：等级 ",
    "Hero finished ": "英雄完成了 ",
    "Evasion : level ": "闪避：等级 ",
    "Multiplies your evasion chance by ": "使你的躲避几率乘以 ",
    "Evasion has reached level ": "闪避已达到等级 ",
    "Reduces environmental penalty in open areas by ": "减少开放区域的环境惩罚 ",
    "Spatial awareness has reached level ": "空间感知睡觉达到等级 ",
    "Combat has reached level ": "战斗达到等级 ",
    "Looted Rat fang": "被掠夺的鼠牙",
    "Weapon mastery has reached level ": "武器精通已达到等级 ",
    "Pest killer has reached level ": "害虫杀手已达到等级 ",
    "Persistence : level ": "持久：等级",
    "[originally ": "[起初 ",
    "Agility increased by ": "敏捷增加 ",
    "HP increased by ": "生命值增加 ",
    "Dexterity increased by ": "灵巧增加 ",
    "Hero is getting stronger. Reached level ": "英雄越来越强了。 达到等级 ",
    "Looted Rat tail": "被掠夺的老鼠尾巴",
    "Tight maneuvers : level ": "紧密动作：等级 ",
    "Reduces environmental penalty in narrow areas by ": "减少狭窄区域的环境惩罚 ",
    "Sleeping : level ": "睡觉 : 等级 ",
    "Sleeping": "睡觉",
    "Quick return to ": "快速返回到 ",
    "Tight maneuvers has reached level ": "紧密动作达到了等级 ",
    "Persistence has reached level ": "持久睡觉达到等级 ",
    "Intuition increased by ": "直觉增加 ",
    "Strength increased by ": "力量增加 ",
    "Farming has reached level ": "耕作达到等级 ",
    "Haggling : level ": "讨价还价 : 等级 ",
    "Literacy : level ": "等级 ",
    "Looted Rat pelt": "被掠夺的老鼠毛皮",
    "Night vision has reached level ": "夜视已经达到等级 ",
    "Reduces darkness penalty (except for 'pure darkness') by ": "将黑暗惩罚（“纯粹黑暗”除外）减少 ",
    "Haggling has reached level ": "讨价还价已达到等级 ",
    "Block :": "格挡 :",
    "Multiplies damage dealt with spears by ": "使长矛造成的伤害乘以 ",
    "Shield blocking : level ": "盾牌格挡：等级 ",
    "Spearmanship : level ": "矛术：等级 ",
    "Patrolling": "巡逻",
    "Axe combat : level ": "斧子战斗 : 等级 ",
    "Dagger combat : level ": "匕首战斗 : 等级 ",
    "Hammer combat : level ": "锤子战斗 : 等级 ",
    "Spearmanship has reached level ": "矛术已达到等级 ",
    "Weapon proficiency : level ": "武器熟练度 : 等级 ",
    "Meditation : level ": "冥想 : 等级 ",
    "Multiplies stamina efficiency by ": "将耐力效率乘以 ",
    "Stamina cost: ": "耐力成本: ",
    "Increases base defense by ": "增加基础防御 ",
    "Tough skin : level ": "坚韧的皮肤 : 等级 ",
    "Focusing your mind": "集中注意力",
    "Carrying heavy things": "搬运重物",
    "Next earnings in: ": "距离下次收益还有: ",
    "Meditation has reached level ": "冥想已经达到了等级 ",
    "Tough skin has reached level ": "坚韧的皮肤已达到等级 ",
    "Broad arc : level ": "宽弧：等级 ",
    "Crushing force : level ": "粉碎之力：等级 ",
    "Brawling : level ": "咆哮：等级 ",
    "Presence sensing : level ": "存在感知: 等级 ",
    "Quick steps : level ": "快步走: 等级 ",
    "Stance mastery : level ": "姿态精通 : 等级 ",
    "Stance proficiency : level ": "姿态熟练 : 等级 ",
    "skin : level ": "皮 : 等级 ",
    "Attack speed: x": "攻击速度: x",
    "Attack power: x": "攻击力: x",
    "Agility: ": "敏捷：",
    "Base value: ": "基础值: ",
    "Base value (weapon * str/": "基础值 (武器 * 力量/",
    "Belmart leaf x": "贝尔玛叶 x",
    "Crit multiplier: ": "暴击乘数: ",
    "Crit rate: ": "暴击率: ",
    "Equipment: ": "装备: ",
    "Golmoon leaf x": "魔月之叶 x",
    "Boar hide x": "野猪皮 x",
    "XP cost scaling: x": "经验成本缩放: x",
    "Wool x": "羊毛 x",
    "Wolf pelt x": "狼皮 x",
    "Level: +": "等级: +",
    "Low quality iron ore x": "低品质铁矿石 x",
    "Oneberry x": "一莓 x",
    "ore x": "矿石 x",
    "Piece of wood x": "木板 x",
    "Rat pelt x": "鼠皮 x",
    "Rat tail x": "鼠尾 x",
    "Rat meat chunks x": "老鼠肉块 x",
    "Reduces extreme darkness penalty by ": "减少极度黑暗惩罚 ",
    "Select a ": "选择一个 ",
    "ingot x": "铸锭 x",
    "Piece of rough wood x": "一块粗糙的木头 x",
    "Skill milestones: ": "技能里程碑: ",
    "Skills: ": "技能: ",
    "Enter the ": "进入 ",
    "Health regeneration  : ": "生命值回复  : ",
    "High quality wolf fang x": "高品质狼牙 x",
    "Glass phial x": "玻璃小瓶 x",
    "High quality boar tusk x": "高品质野猪牙 x",
    "Stance: x": "姿态: x",
    "Stamina regeneration  : ": "耐力恢复：",
    "AP:  ": "攻击力:  ",
    "Woodcutting : level ": "伐木 : 等级 ",
    "Gained \"Piece of rough wood\" x": "获得“一块粗糙的木头” x",
    "Gathering wood": "收集木材",
    "Pest slayer : level ": "捉害虫  : 等级 ",
    "Mining : level ": "采矿 : 等级 ",
    "Alchemy : level ": "炼金 : 等级 ",
    "Forging : level ": "锻造 : 等级 ",
    "Herbalism : level ": "草药学 : 等级 ",
    "Cooking : level ": "烹饪 : 等级 ",
    "Crafting : level ": "制作 : 等级 ",
    "Go to ": "前往 ",
    "Smelting : level ": "冶炼 : 等级 ",
    "Equilibrium : level ": "平衡 : 等级 ",
    "Multiplies agility by ": "敏捷乘以 ",
    "Trying to keep your balance": "努力保持平衡",
    "Getting 1 base xp per in-game minute to ????? ": "在游戏中每分钟获得 $1 ????? 经验 ",
    "Shield blocking has reached level ": "盾牌格挡达到等级 ",
    "Block strength: x": "格挡强度：x",
    "Getting 1 base xp per gathering cycle to ????? ": "获得1个基础经验，每收集周期？？？？？",
    "Tending to animals": "照料动物",
    "Animal handling : level ": "动物处理：等级",
    "Animal handling has reached level ": "动物处理已达到等级 ",
    "Gained \"Wool\" x": "获得了 “羊毛” x",
    "Component tier: ": "组件层级: ",
    "Processed wood x": "加工木头 x",
    "Processed rough wood x": "加工粗糙的木头 x",
    "Piece of boar leather x": "一块野猪皮 x",
    "Piece of wolf leather x": "一块狼皮 x",
    "Piece of wolf rat leather x": "一块狼鼠皮 x",
    "vest, ": "背心, ",
    "pants, ": "裤子, ",
    "Created Rat meat chunks x": "制作的老鼠肉块 x",
    "Created Processed rough wood x": "制作的粗糙的木头 x",
    "Created Piece of boar leather x": "制作的野猪皮 x",
    "Created Piece of wolf leather x": "制作的狼皮 x",
    "Created Piece of wolf rat leather x": "制作的狼鼠皮 x",
    "Boar leather ": "野猪皮",
    "Wolf leather ": "狼皮",
    "Wool cloth x": "羊毛布 x",
    "Size-specific attack power: x": "特定尺寸的攻击力：x",
    "Swinging the pickaxe": "挥舞镐子",
    "Environment: x": "环境: x",
    "Looted \"Rat pelt\" x": "掠夺了 “鼠皮” x",
    "Looted \"Rat tail\" x": "掠夺了 “鼠尾” x",
    "Looted \"Rat fang\" x": "掠夺了 “鼠牙” x",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "Enemy groups left: ": "剩余敌人：",
    "Enemy groups left:": "剩余敌人：",
    "No active effects            ": "无",
    "Attack points, a total value of everything that contributes to the chance to hit an enemy, except for some situational skills and modifiers.": "攻击点，即所有有助于击中敌人的机会的总价值，除了一些情境技能和修饰符之外。",
    ": ???": ": ???",
    "nothing)": "无)",
    ",": ",",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)h([\d\.]+)m$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^防御(.+)$/,
    /^等级(.+)$/,
    /^经验(.+)$/,
    /^减少(.+)$/,
    /^正在(.+)$/,
    /^收集(.+)$/,
    /^生命(.+)$/,
    /^家长(.+)$/,
    /^空间(.+)$/,
    /^敏捷(.+)$/,
    /^耐力(.+)$/,
    /^攻速(.+)$/,
    /^基础(.+)$/,
    /^跑步(.+)$/,
    /^巡逻(.+)$/,
    /^耕作(.+)$/,
    /^举重(.+)$/,
    /^讨价还价(.+)$/,
    /^武器(.+)$/,
    /^暴击(.+)$/,
    /^最大(.+)$/,
    /^\n等级(.+)$/,
    /^只是(.+)$/,
    /^战斗(.+)$/,
    /^阅读(.+)$/,
    /^闪避(.+)$/,
    /^睡觉(.+)$/,
    /^最多(.+)$/,
    /^剑术(.+)$/,
    /^攻击(.+)$/,
    /^价值(.+)$/,
    /^便宜(.+)$/,
    /^id: (.+)$/,
    /^鼠(.+)$/,
    /^将(.+)$/,
    /^斧(.+)$/,
    /^质量(.+)$/,
    /^成本(.+)$/,
    /^(.+)经验增益$/,
    /^(.+)速度$/,
    /^(.+)攻击力$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^x ([\d\.]+)$/,
    /^\+ ([\d\.]+)$/,
    /^ ([\d\.]+)$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Lowers trader cost multiplier to (.+) of original value$/, '将交易者成本乘数降低至原始价值的 $1'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Multiplies damage dealt in unarmed combat by (.+). \nMultiplies attack speed and AP in unarmed combat by (.+)$/, '徒手格斗的伤害增加 $1。徒手格斗的攻击速度和攻击力增加 $2'],
    [/^Getting (.+) base xp per in\-game minute to Farming \(Max\)$/, '在游戏中每分钟获得 $1 基础 农场 经验（最多）'],
    [/^Getting (.+) base xp per gathering cycle to Mining \((.+)\)$/, '采矿获得 $1 基础经验每收集周期（$2）'],
    [/^Getting (.+) base xp per gathering cycle to Woodcutting \((.+)\)$/, '伐木获得 $1 基础经验每收集周期（$2）'],
    [/^Getting (.+) base xp per gathering cycle to Animal handling \((.+)\)$/, '动物处理获得 $1 基础经验每收集周期（$2）'],
    [/^Getting (.+) base xp per in\-game minute to Meditation \((.+)\)$/, '在游戏中每分钟获得 $1 基础 冥想 经验（$2）'],
    [/^Getting (.+) base xp per in\-game minute to Running \((.+)\)$/, '在游戏中每分钟获得 $1 基础 跑步 经验（$2）'],
    [/^Getting (.+) base xp per in\-game minute to Weightlifting \((.+)\)$/, '在游戏中每分钟获得 $1 基础 举重 经验（$2）'],
    [/^Getting (.+) base xp per in\-game minute to Equilibrium \((.+)\)$/, '在游戏中每分钟获得 $1 基础 平衡 经验（$2）'],
    [/^Getting (.+) base xp per in\-game minute to Weightlifting \((.+)\)$/, '在游戏中每分钟获得 $1 基础 举重 经验（$2）'],
    [/^Getting (.+) base xp per in\-game minute to Spatial awareness \((.+)\)$/, '在游戏中每分钟获得 $1 基础 空间感知 经验（$2）'],
    [/^Increases low stamina stat multiplier to x(.+) \(originally x(.+)\)$/, '将低耐力属性增加到 x$1 \(原来是 x$2 \)'],
    [/^Can block up to (.+) damage \[base: (.+)\]$/, '可以格挡最多 $1 伤害 \[基础: $2\]'],
    [/^Every (.+) minutes, chance to find:$/, '每隔 $1 分钟，就有几率发现：'],
    [/^Every (.+) hour, chance to find:$/, '每隔 $1 小时，就有几率发现：'],
    [/^Every (.+) hours, chance to find:$/, '每隔 $1 小时，就有几率发现：'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Can block up to: (.+) damage \[base: (.+)\]$/, '最多可格挡：$1 点伤害 \[基础：$2\]'],
    [/^Getting (.+) xp per in-game minute to Running$/, '跑步 时每分钟\(游戏内时间\)获得 $1 经验'],
    [/^Getting (.+) xp per in-game minute to Farming$/, '耕作 时每分钟\(游戏内时间\)获得 $1 经验'],
    [/^Getting (.+) xp per in-game minute to Weightlifting$/, '举重 时每分钟\(游戏内时间\)获得 $1 经验'],
    [/^Getting (.+) xp per in-game minute to Spatial awareness$/, '空间感知 时每分钟\(游戏内时间\)获得 $1 经验'],
    [/^Increases block chance by flat (.+). Increases blocked damage by (.+)$/, '格挡几率增加 $1。 格挡伤害增加 $2'],
    [/^Reading it provided (.+) with:$/, '阅读它为 $1 提供了：'],
    [/^There\'s not enough time left to earn more, but (.+) might still learn something...$/, '没有足够的时间来赚取更多，但 $1 仍然可以学到一些东西......'],
    [/^Reading the book, (.+) hour left$/, '正在看书，还有 $1 小时'],
    [/^Reading the book, (.+) hours left$/, '正在看书，还有 $1 小时'],
    [/^Reading the book, (.+) minutes left$/, '正在看书，还有 $1 分钟'],
    [/^Reading the book, (.+) hour left$/, '正在看书，还有 $1 小时'],
    [/^Reading the book, (.+) hour left(.+)$/, '正在看书，还有 $1 小时$2'],
    [/^Reading the book, (.+) hours left$/, '正在看书，还有 $1 小时'],
    [/^Reading the book, (.+) hours left(.+)$/, '正在看书，还有 $1 小时$2'],
    [/^Reading the book, (.+) minutes left(.+)$/, '正在看书，还有 $1 分钟$2'],
    [/^(.+) \"Low quality iron ore\" at (.+)$/, '$1 \“低品质铁矿石\” 在 $2'],
    [/^(.+) \"Iron ore\" at (.+)$/, '$1 \铁矿石\” 在 $2'],
    [/^(.+) \"Wool\" at (.+)$/, '$1 \“羊毛\” 在 $2'],
    [/^\"Mining\" skill lvl (.+) to (.+)$/, '“采矿”技能等级 $1 到 $2'],
    [/^(.+) \"Piece of rough wood\" at (.+)$/, '$1 \“粗糙的木头\” 在 $2'],
    [/^(.+).\nMultiplies AP with axes by (.+)$/, '$1.\n使用 斧头 时 攻击力 乘以 $2'],
    [/^(.+).\nMultiplies AP with daggers by (.+)$/, '$1.\n使用 匕首 时 攻击力 乘以 $2'],
    [/^(.+).\nMultiplies AP with hammers by (.+)$/, '$1.\n使用 锤子 时 攻击力 乘以 $2'],
    [/^(.+).\nMultiplies AP with spears by (.+)$/, '$1.\n使用 矛 时 攻击力 乘以 $2'],
    [/^(.+).\nMultiplies AP with swords by (.+)$/, '$1.\n使用 剑 时 攻击力 乘以 $2'],
    [/^(.+) is getting stronger. Reached level (.+)$/, '$1 越来越强了。 达到等级 $2'],
    [/^(.+) finished patrolling$/, '$1 完成了巡逻'],
    [/^(.+) finished mining$/, '$1 完成了采矿'],
    [/^(.+) finished running$/, '$1 完成了跑步'],
    [/^(.+) finished weightlifting$/, '$1 完成了举重'],
    [/^(.+) earned ([\d\.,]+)$/, '$1 赚取了 $2'],
    [/^(.+) evaded an attack$/, '$1 躲避了攻击'],
    [/^(.+) has missed$/, '$1 未命中'],
    [/^(.+) finished plowing the fields$/, '$1 完成了耕作'],
    [/^(.+) has lost consciousness$/, '$1 失去了知觉'],
    [/^Obtained (.+) for clearing (.+) for the first time$/, '首次清除 $1 获得 $2 经验值'],
    [/^Obtained additional (.+) for clearing (.+)$/, '清理 $1 获得额外 $2 经验值'],
    [/^Reduces low stamina penalty by (.+) percentage points$/, '减少低耐力惩罚 $1 个百分点'],
	[/^([\d\.]+)\/([\d\.]+) xp$/, '$1\/$2 经验值'],
	[/^([\d\.]+)\/([\d\.]+) hp$/, '$1\/$2 生命值'],
	[/^([\d\.]+)\/([\d\.]+) stamina$/, '$1\/$2 耐力'],
	[/^([\d\.]+)\/([\d\.]+) mana$/, '$1\/$2 法力'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^Def: ([\d\.]+)$/, '防御: $1'],
    [/^Defense: ([\d\.]+)$/, '防御: $1'],
    [/^Defense: ([\d\.]+)\-([\d\.]+)$/, '防御: $1\-$2'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^XP gain: x([\d\.,]+)$/, '经验增益: x$1'],
    [/^Pays ([\d\.,]+)$/, '支付 $1'],
    [/^AP  ([\d\.,]+)$/, '攻击 $1'],
    [/^Value: ([\d\.,]+)$/, '价值: $1'],
    [/^Atk spd: ([\d\.,]+)$/, '攻速: $1'],
    [/^Attack: ([\d\.,]+)$/, '攻击: $1'],
    [/^lvl ([\d\.,]+)$/, '等级 $1'],
    [/^lvl ([\d\.,]+): \+([\d\.,]+) dex$/, '等级 $1：\+$2 灵巧'],
    [/^lvl ([\d\.,]+): \+([\d\.,]+) str$/, '等级 $1：\+$2 力量'],
    [/^lvl ([\d\.,]+): \+([\d\.,]+) agl$/, '等级 $1：\+$2 敏捷'],
    [/^lvl ([\d\.,]+): \+([\d\.,]+) agl,$/, '等级 $1：\+$2 敏捷,'],
    [/^lvl ([\d\.,]+): \+([\d\.,]+) stamina$/, '等级 $1：\+$2 耐力'],
    [/^lvl ([\d\.,]+): \+([\d\.,]+) int$/, '等级 $1：\+$2 直觉'],
    [/^lvl ([\d\.,]+): x([\d\.,]+) hero xp gain$/, '等级 $1：x$2 英雄经验增益'],
    [/^lvl ([\d\.,]+): x([\d\.,]+) Combat xp gain$/, '等级 $1：x$2 战斗经验增益'],
    [/^x([\d\.]+), Rat fang x([\d\.]+)$/, 'x$1，鼠牙 x$2'],
    [/^x([\d\.]+) Shield blocking xp gain$/, 'x$1 盾牌格挡经验增益'],
    [/^x([\d\.]+) Evasion xp gain$/, 'x$1 闪避经验增益'],
    [/^x([\d\.]+) Combat xp gain$/, 'x$1 战斗经验增益'],
    [/^x([\d\.]+) all skill xp gain$/, 'x$1 所有技能经验增益'],
    [/^x([\d\.]+) all xp gain$/, 'x$1 全部经验增益'],
    [/^x([\d\.]+) Presence sensing xp gain$/, 'x$1 存在感经验增益'],
    [/^x([\d\.]+) hero xp gain$/, 'x$1 英雄经验增益'],
    [/^x([\d\.]+) combat xp gain$/, 'x$1 战斗经验增益'],
    [/^x([\d\.]+) attack speed$/, 'x$1 攻击速度'],
    [/^x([\d\.]+) attack power$/, 'x$1 攻击力'],
    [/^x([\d\.]+) str$/, 'x$1 力量'],
    [/^x([\d\.]+) stamina$/, 'x$1 耐力'],
    [/^x([\d\.]+) agl$/, 'x$1 敏捷'],
    [/^x([\d\.]+) stamina efficiency$/, 'x$1 耐力效率'],
    [/^\nlvl ([\d\.,]+): Unlocked skill \"Meditation\"$/, '\n等级 $1：解锁技能 “冥想”'],
    [/^\nlvl ([\d\.,]+): \+(.+) int$/, '\n等级 $1：\+$2 直觉'],
    [/^\nlvl ([\d\.,]+): \+(.+) agl$/, '\n等级 $1：\+$2 敏捷'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, , \+(.+) dex,$/, '\n等级 $1：\+$2 力量，\+$3 灵巧，'],
    [/^\nlvl ([\d\.,]+): \+(.+) agl,$/, '\n等级 $1：\+$2 敏捷，'],
    [/^\nlvl ([\d\.,]+): \+(.+) dex,$/, '\n等级 $1：\+$2 灵巧，'],
    [/^\nlvl ([\d\.,]+): \+(.+) str,$/, '\n等级 $1：\+$2 力量，'],
    [/^\nlvl ([\d\.,]+): x(.+) str$/, '\n等级 $1：x$2 力量'],
    [/^\nlvl ([\d\.,]+): x(.+) Presence sensing xp gain$/, '\n等级 $1：x$2 存在感经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) str$/, '\n等级 $1：\+$2 力量'],
    [/^\nlvl ([\d\.,]+): \+(.+) dex$/, '\n等级 $1：\+$2 灵巧'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, x(.+) str, x(.+) stamina$/, '\n等级 $1：\+$2 力量, x$3 力量, x$4 耐力'],
    [/^\nlvl ([\d\.,]+): \+(.+) hp, x(.+) hp, x(.+) all xp gain, x(.+) Meditation xp gain$/, '\n等级 $1：\+$2 生命值, x$3 生命值, x$4 所有经验增益, x$5 冥想 经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) agl, x(.+) agl, x(.+) stamina$/, '\n等级 $1：\+$2 敏捷, x$3 敏捷, x$4 耐力'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, x(.+) Weightlifting xp gain$/, '\n等级 $1：\+$2 力量, x$3 举重经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, , x(.+) Weightlifting xp gain$/, '\n等级 $1：\+$2 力量, x$3 举重经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, , x(.+) Brawling xp gain$/, '\n等级 $1：\+$2 力量, x$3 争吵经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) dex, \+(.+), , x(.+) Brawling xp gain$/, '\n等级 $1：\+$2 灵巧, \+$3 耐力, , x$4 争吵经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, x(.+) Unarmed xp gain$/, '\n等级 $1：\+$2 力量, x$3 徒手经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) agl, x(.+) agl$/, '\n等级 $1：\+$2 敏捷, x$3 敏捷'],
    [/^\nlvl ([\d\.,]+): \+(.+) agl, x(.+) stamina$/, '\n等级 $1：\+$2 敏捷, x$3 耐力'],
    [/^\nlvl ([\d\.,]+): \+(.+) agl, x(.+) stamina efficiency$/, '\n等级 $1：\+$2 敏捷, x$3 耐力效率'],
    [/^\nlvl ([\d\.,]+): \+(.+) stamina, , x(.+) hero xp gain$/, '\n等级 $1：\+$2 耐力, x$3 英雄经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) stamina, x(.+) xp gain$/, '\n等级 $1：\+$2 耐力, x$3 经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) dex, x(.+) Combat xp gain$/, '\n等级 $1：\+$2 灵巧, x$3 战斗经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) dex, , x(.+) Combat xp gain$/, '\n等级 $1：\+$2 灵巧, x$3 战斗经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) agl, \+(.+) stamina$/, '\n等级 $1：\+$2 敏捷, \+$3 耐力'],
    [/^\nlvl ([\d\.,]+): \+(.+) agl, \+(.+) crit dmg$/, '\n等级 $1：\+$2 敏捷, \+$3 暴击伤害'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, \+(.+) crit dmg$/, '\n等级 $1：\+$2 力量, \+$3 暴击伤害'],
    [/^\nlvl ([\d\.,]+): \+(.+) crit rate, \+(.+) crit dmg$/, '\n等级 $1：\+$2 暴击率, \+$3 暴击伤害'],
    [/^\nlvl ([\d\.,]+): \+(.+) crit dmg, \+(.+) crit rate$/, '\n等级 $1：\+$2 暴击伤害, \+$3 暴击率'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, \+(.+) crit rate$/, '\n等级 $1：\+$2 力量, \+$3 暴击率'],
    [/^\nlvl ([\d\.,]+): \+(.+) dex, \+(.+) stamina$/, '\n等级 $1：\+$2 灵巧, \+$3 耐力'],
    [/^\nlvl ([\d\.,]+): \+(.+) dex, \+(.+) stamina,$/, '\n等级 $1：\+$2 灵巧, \+$3 耐力，'],
    [/^\nlvl ([\d\.,]+): \+(.+) dex, \+(.+) str,$/, '\n等级 $1：\+$2 灵巧, \+$3 力量，'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, \+(.+) stamina$/, '\n等级 $1：\+$2 力量, \+$3 耐力'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, \+(.+) stamina,$/, '\n等级 $1：\+$2 力量, \+$3 耐力，'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, \+(.+) dex,$/, '\n等级 $1：\+$2 力量, \+$3 灵巧,'],
    [/^lvl ([\d\.,]+): \+(.+) stamina, x(.+) all skill xp gain$/, '等级 $1：\+$2 耐力, x$3 所有技能经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) stamina, , x(.+) all xp gain$/, '\n等级 $1：\+$2 耐力, x$3 所有经验增益'],
    [/^lvl ([\d\.,]+): \+(.+) stamina, , x(.+) all skill xp gain$/, '等级 $1：\+$2 耐力, x$3 所有技能经验增益'],
    [/^\nlvl ([\d\.,]+): x(.+) Combat xp gain$/, '\n等级 $1：x$2 战斗经验增益'],
    [/^\nlvl ([\d\.,]+): x(.+) int, x(.+) Combat xp gain$/, '\n等级 $1：x$2 直觉，x$3 战斗经验增益'],
    [/^\nlvl ([\d\.,]+): x(.+) dex, x(.+) Evasion xp gain, x(.+) Shield blocking xp gain$/, '\n等级 $1：x$2 灵巧，x$3 闪避经验增益，x$4 盾牌格挡经验增益'],
    [/^\nlvl ([\d\.,]+): x(.+) dex, x(.+) Evasion xp gain, x(.+) xp gain$/, '\n等级 $1：x$2 灵巧，x$3 闪避经验增益，x$4 经验增益'],
    [/^\nlvl ([\d\.,]+): x(.+) all skill xp gain$/, '\n等级 $1：x$2 全部技能经验增益'],
    [/^\nlvl ([\d\.,]+): x(.+) hp$/, '\n等级 $1：x$2 生命值'],
    [/^\nlvl ([\d\.,]+): x(.+) all xp gain$/, '\n等级 $1：x$2 全部经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) int, , x(.+) xp gain$/, '\n等级 $1：\+$2 直觉，x$3 经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) agl, x(.+) Equilibrium xp gain$/, '\n等级 $1：\+$2 敏捷，x$3 平衡经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) agl, , x(.+) xp gain$/, '\n等级 $1：\+$2 敏捷，x$3 经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) int, x(.+) Combat xp gain$/, '\n等级 $1：\+$2 直觉，x$3 战斗经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) int, , x(.+) Combat xp gain$/, '\n等级 $1：\+$2 直觉，x$3 战斗经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) int, x(.+) int, x(.+) all xp gain$/, '\n等级 $1：\+$2 直觉，x$3 直觉，x$4 全部经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) hp, x(.+) hp, x(.+) all xp gain$/, '\n等级 $1：\+$2 生命值，x$3 生命值，x$4 全部经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, \+(.+) dex, \+(.+) agl, x(.+) Running xp gain$/, '\n等级 $1：\+$2 力量，x$3 灵巧，x$4 敏捷，x$5 跑步经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, \+(.+) dex, \+(.+) agl, x(.+) Weightlifting xp gain$/, '\n等级 $1：\+$2 力量，x$3 灵巧，x$4 敏捷，x$5 举重经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, \+(.+) dex, \+(.+) agl, , x(.+) Weightlifting xp gain$/, '\n等级 $1：\+$2 力量，x$3 灵巧，x$4 敏捷，x$5 举重经验增益'],
    [/^lvl ([\d\.,]+): \+(.+) int, x(.+) all xp gain, x(.+) Presence sensing xp gain$/, '等级 $1：\+$2 直觉，x$3 全部经验增益，x$4 存在感经验增益'],
    [/^lvl ([\d\.,]+): \+(.+) int, , x(.+) all xp gain, x(.+) Presence sensing xp gain$/, '等级 $1：\+$2 直觉，x$3 全部经验增益，x$4 存在感经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) int, x(.+) Presence sensing xp gain$/, '\n等级 $1：\+$2 直觉，x$3 存在感经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) int, , x(.+) Presence sensing xp gain$/, '\n等级 $1：\+$2 直觉，x$3 存在感经验增益'],
    [/^lvl ([\d\.,]+): \+(.+) hp, x(.+) hp, x(.+) all xp gain$/, '等级 $1：\+$2 生命值，x$3 生命值，x$4 全部经验增益'],
    [/^lvl ([\d\.,]+): \+(.+) int, x(.+) Night vision xp gain$/, '等级 $1：\+$2 直觉，x$3 夜视经验增益'],
    [/^lvl ([\d\.,]+): \+(.+) int, , x(.+) Night vision xp gain$/, '等级 $1：\+$2 直觉，x$3 夜视经验增益'],
    [/^lvl ([\d\.,]+): \+(.+) str, x(.+) Weightlifting xp gain$/, '等级 $1：\+$2 力量，x$3 举重经验增益'],
    [/^lvl ([\d\.,]+): \+(.+) str, , x(.+) xp gain$/, '等级 $1：\+$2 力量，x$3 举重经验增益'],
    [/^lvl ([\d\.,]+): x(.+) Evasion xp gain, x([\d\.,]+) Shield blocking xp gain$/, '等级 $1：x$2 闪避经验增益，x$3 盾牌格挡经验增益'],
    [/^lvl ([\d\.,]+): x(.+) hp$/, '等级 $1：x$2 生命值'],
    [/^\nlvl ([\d\.,]+): x(.+) Evasion xp gain, x([\d\.,]+) Shield blocking xp gain$/, '\n等级 $1：x$2 闪避经验增益，x$3 盾牌格挡经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, \+(.+) stamina, , x(.+) xp gain$/, '\n等级 $1：\+$2 力量，x$3 耐力，x$4 经验增益'],
    [/^\nlvl ([\d\.,]+): x(.+) dex, x(.+) xp gain, x(.+) xp gain$/, '\n等级 $1：x$2 灵巧，x$3 闪避经验增益，x$4 经验增益'],
    [/^\nlvl ([\d\.,]+): \+(.+) str, , x(.+) xp gain$/, '\n等级 $1：\+$2 力量, x$3 经验增益'],
    [/^\nlvl ([\d\.,]+): x(.+) xp gain$/, '\n等级 $1：x$2 经验增益'],
    [/^Lvl: ([\d\.,]+)$/, '等级: $1'],
    [/^Starving wolf rat was critically hit for ([\d\.,]+) dmg$/, '饥饿的狼鼠遭到重击受到 $1 点伤害'],
    [/^Wolf rat was critically hit for ([\d\.,]+) dmg$/, '狼鼠遭到重击受到 $1 点伤害'],
    [/^Hero was critically hit for ([\d\.,]+) dmg$/, '英雄遭到重击受到 $1 点伤害'],
    [/^(.+) was critically hit for ([\d\.,]+) dmg$/, '$1 遭到重击受到 $2 点伤害'],
    [/^(.+) partially blocked, was critically hit for ([\d\.,]+) dmg$/, '$1 格挡了部分伤害，并遭到重击受到 $2 点伤害'],
    [/^(.+) finished animal care$/, '$1 完成的动物护理'],
    [/^(.+) finished balancing$/, '$1 完成的平衡'],
    [/^(.+) finished meditating$/, '$1 完成的冥想'],
    [/^(.+) finished woodcutting$/, '$1 完成的伐木'],
    [/^(.+) blocked an attack$/, '$1 格挡了一次攻击'],
    [/^ x([\d\.,]+), \"Rat fang\" x([\d\.,]+)$/, ' x$1, \"鼠牙\" x$2'],
    [/^AP x(.+) \[base: x(.+)\]$/, 'AP x$1 \[基数: x$2\]'],
    [/^EP x(.+) \[base: x(.+)\]$/, 'EP x$1 \[基数: x$2\]'],
    [/^Thanks to (.+) reaching new milestone, (.+) gained:$/, '由于 $1 达到新的里程碑，$2 获得了：'],
    [/^Can block up to ([\d\.,]+) damage$/, '最多可以格挡 $1 点伤害'],
    [/^ has reached level ([\d\.,]+)$/, ' 达到等级 $1'],
    [/^\+([\d\.,]+) str$/, '\+$1 力量'],
    [/^\+([\d\.,]+) hp$/, '\+$1 生命值'],
    [/^Level: ([\d\.,]+)$/, '等级：$1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Time to read: ([\d\.,]+) minutes$/, '阅读时间：$1 分钟'],
    [/^Your purse contains: ([\d\.,]+)$/, '你的钱包里有：$1'],
    [/^Hero was hit for (.+) dmg$/, '英雄被击中并受到 $1 伤害'],
    [/^Wolf rat was hit for (.+) dmg$/, '狼鼠被击中并受到 $1 伤害'],
    [/^Starving wolf rat was hit for (.+) dmg$/, '饥饿的狼鼠被击中并受到 $1 伤害'],
    [/^(.+)partially blocked, was hit for (.+) dmg$/, '$1被击中但是格挡了部分伤害，受到 $2 伤害'],
    [/^(.+) was hit for (.+) dmg$/, '$1 被击中并受到 $2 伤害'],
    [/^Monday (.+)$/, '星期一 $1'],
    [/^Tuesday (.+)$/, '星期二 $1'],
    [/^Wednesday (.+)$/, '星期三 $1'],
    [/^Thursday (.+)$/, '星期四 $1'],
    [/^Friday (.+)$/, '星期五 $1'],
    [/^Saturday (.+)$/, '星期六 $1'],
    [/^Sunday (.+)$/, '星期日 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);