/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Click on blocks to unfold their content": "点击区块展开它们的内容",
    "v0.2.0\n    - fixed all the bugs I managed to find; \n    fighting against groups now should work without any issues (other than balance)\n\n    - restructured a lot of code, mostly moved stuff to new places,\n    but also created some new methods for updating the display\n\n    - moved the page selection buttons to the top\n    - switched from fontawesome to google icons": "v0.2.0\n -修复了我设法找到的所有错误;\n对抗团体现在应该没有任何问题(除了平衡)\n\n -重组了很多代码，主要是将东西移动到新的地方，\n \n但也创建了一些新的方法来更新显示\n\n -将页面选择按钮移动到顶部\n -从fontawesome切换到Google ICONS",
    "v0.4.0\n    - introduced combat stances, talk with village guard to unlock (ask him for tips if you already met him earlier); lots of names were suggested by Varian on our discord channel\n    - some combat related skills now gain xp even if their original condition (e.g. succeeding in some action) is not fulfilled, although at half the efficiency\n    - the rat saga continues\n    - a bit more content after leaving the village\n    - added some background \"sounds\"\n    - new skills and activities (check training options in village and cave, they might be instantly unlocked if you are far enough)\n    - rebalance; changes to some displayed texts\n    - modified changelog and help page to a form easier to navigate\n    - regeneration when sleeping now scales with \"Sleeping\" skill\n    - trade all button + another trade bugfix (plz let it be the last one)\nv0.4.0a\n    - balance changes\n    - switching weapons now won't make dead enemies suddenly start attacking again\n    - CSS fixes\n    - dialogue text fixes\n    - level bonuses from \"Presence sensing\" skill, expanded bonuses for some other skills\nv0.4.0b\n    - more balance changes\n    - changed some background 'sounds'\n    - bugfixes\nv0.4.0c\n    - fixed bug with doubled stamina usage when some attacks would one-shot an enemy wave\n    - reduced frequency of background 'sounds'\n    - raised max level of presence sensing but reduced initial xp cost\n    - fixed rounding of displayed health\n    - fixed doubling of some skill bars\n    - fixed a bug where if reading a book inventory would get sorted every irl second\n    - 'broad arc' stamina cost raised to 4\nv0.4.0d\n    - hitcount of multi-target stances now properly updates in their descriptions when needed\n    - 'suspicious wall', 'village guard' and 'suspicious man' are no longer 'small' targets\n    - 'broad arc' dmg multiplier reduced to 0.4\n    - 'cave depths' location is now a tiny bit harder\n    - location types now how their stage displayed (e.g 'dark III')\n    - fixed 'quick steps' skill's too low xp cost\nv0.4.0e\n    - stabilized enemy attack timers (based on expected time vs actual time) to hopefully fix the issue with enemy attacks firing slower than expected\nv0.4.0f\n    - fixed issue with xp multiplier rewards from skill levels not working properly after reloading the game\nv0.4.0g\n    - fixed stance skills having no effect\n    - stamina efficiency in 'Data' is now shown with 2 decimal places\n    - minor CSS fix\nv0.4.0h\n    - fixed wrong stance names in some skill descriptions\n    - crit rate / crit power breakdown is now shown with 2 decimal places\nv0.4.0i\n    - fixed a bug where when entering activity with a maxxed out skill, xp% would be NaN\n    - CSS fixes for inventory\nv0.4.0j\n    - fixed multi-trade buttons that were broken by previous patch\nv0.4.0k\n    - simplified some code\nv0.4.0l\n    - CSS fixes for inventory\nv0.4.0m\n    - fixed skill-specific xp bonuses not working\n    - added a few more skill level rewards\n    - slightly reduced xp multipliers and crit rate from skill levels\nv0.4.0n\n    - another CSS fix for inventory\n    - another bugfix for trade (displayed value vs actual value sometimes differed)\nv0.4.0o\n    - equalized base xp costs for stance skills at 60, modified how they gain xp\n    - added parent skill for stance skills\n    - added some more names to existing skills": "V0.4.0 \n -引入战斗姿态，与村庄警卫交谈解锁(如果你之前已经见过他，请向他询问技巧)瓦里安在我们的不和谐频道上提出了许多名字-一些战斗相关技能现在获得经验，即使他们的原始条件(例如在某些行动中取得成功)没有得到满足，尽管在一半的效率下-老鼠的故事继续-在离开村庄后增加了一些背景“声音”-新技能和活动(检查村庄和洞穴的训练选项，如果你足够远，它们可能会立即解锁)\n -再平衡;改变了一些显示的文本\n -修改的变更日志和帮助页面到一个更容易导航的形式\n -再生睡觉时现在缩放\“睡觉\”技能\n -交易所有按钮+另一个交易错误修复(请让它是最后一个)\nv0.4.0a\n -平衡变化\n -切换武器现在不会使死亡的敌人突然开始再次攻击\n - CSS修复\n -对话文本修复\n -级别奖金从\“存在感\”技能，扩大了一些其他技能奖金\ nv0.4.0b \ n -更平衡的变化\ n -改变了一些背景'声音' \ n -修正\ nv0.4.0c \ n -固定错误一倍耐力一些攻击时使用一次性敌人波\ n -降低频率的背景'声音' \ n - max水平存在传感但减少最初的xp成本\ n -固定圆显示健康\ n -固定翻倍的一些技巧酒吧\ n -固定一个bug,如果库存会阅读一本书\n -“宽弧”的耐力消耗提高到4\nv0.4.0d\n -多目标姿态的命中数现在在需要时正确更新了他们的描述\n -“可疑的墙”“村庄卫队”和“可疑的男人”不再是“小”目标\ n -广泛的弧的dmg乘数降低到0.4 \ n -洞穴深处的位置现在是一点点困难\ n -位置类型现在阶段如何显示(如黑暗III) \ n -固定“快速步骤”技能太xp成本低\ nv0.4.0e \ n -稳定敌人攻击计时器(基于预计时间和实际时间)希望解决问题的敌人攻击发射比预期慢\ nv0.4.0f \ n - xp乘数的固定问题奖励从技能水平不正常工作后重新加载游戏\ nv0.4.0g \ n -固定立场技能没有影响\ n -耐力效率的数据现在有2位小数\ n -小CSS修复\ nv0.4.0h \ n -固定错误的立场名称在一些技能描述\ n -暴击率/暴击的力量击穿现在显示小数点后2 \ nv0.4.0i \ n -固定一个bug,当进入活动刷爆技能,xp %将南\ n - CSS修复库存\ nv0.4.0j \ n -固定总按钮是前片破碎的\ nv0.4.0k \ n -简化一些代码\ nv0.4.0l \ n - CSS修复库存\ nv0.4.0m固定专门技能xp奖金不工作\ \ n - n -添加更多的技能水平奖励\ n -略减少xp乘数和暴击率从技能水平\ nv0.4.0n \ n -另一个CSS解决库存\ n -贸易的另一个错误修复(有时显示值与实际值不同)\nv0.4.0o\n -平衡基础经验成本的立场技能在60，修改了他们如何获得经验\n -增加了立场技能的父技能\n -增加了一些更多的名称到现有的技能",
    "v0.3.5\n    - reworked economy (drop rates no longer go down, instead price of enemy loot goes down as more and more is sold, they also slowly recover over time; solution suggested by 10mart10 on our discord channel)\n    - added quick travel to [last combat location] and to [last location where player slept]\n    - xp multipliers are now displayed - for skills in their onhover tooltip, for hero in data tab\n    - shield blocking skill now increases max dmg than can be blocked; block chance reduced by 5% points (goes from 75% to 95%)\n      it also has 30 levels instead of 20 now\n    - combat areas now have their descriptions available as tooltips when hovering over their name\n    - added more entries to the \"help\" section\n    - nerfed xp rewards for clearing both cave areas, added xp rewards for both forest areas\n    - buffed wolves (probably not enough, you guys are too strong)\n    - some other balance changes for skills, hero and items\n    - enemies in combat now display their chance to hit hero and to dodge hero's attack, instead of AP/EP\n    - some style fixes, styling for money\n    - fixed parent skill xp gain (now they will keep up in xp with their most leveled child)\n    - added skill sorting (by name and by level); fixed inventory sorting; you can now also click button again to reverse sort direction (switch between ascending and descending)\nv0.3.5a\n    - minor CSS fix\nv0.3.5b\n    - equipment display fix\n    - trade bug fix\nv0.3.5c\n    - fixed skill rewards being added twice\nv0.3.5d\n    - some values wouldn't refresh properly\n    - added consolelogging of some warnings in case of unexpected results\n    - fixed some rounding issues\n    - some balance changes\n    - another trade fix\nv0.3.5e\n    - xp bonus from parent skill is now included in xp gains in skill tooltip\n    - minor balance change\n    - fixed some styling\nv0.3.5f\n    - (hopefully) fixed issue with attack speed\nv0.3.5g\n    - fixed unarmed attack speed bonus not being added\nv0.3.5h\n    - fixed minor bug with loading older saves\nv0.3.5i\n    - fixed attacks getting faster on 0 stamina": "V0.3.5 \n -重制经济(掉落率不再下降，相反，敌人的战利品价格会随着出售数量的增加而下降，他们也会随着时间的推移慢慢恢复;解决方案由10mart10在我们的discord频道上提出)-增加了快速旅行到[最后战斗地点]和[玩家最后睡觉的地方]- xp乘数现在显示-对于技能在他们的悬停工具提示中，对于英雄在数据标签中-盾挡技能现在增加最大伤害比可以阻挡格挡几率减少了5%(从75%到95%)\n它也有30个等级，而不是现在的20个\n -战斗区域现在有他们的描述，当他们的名字悬空时，可以作为工具提示\n -在\n“帮助\”部分添加了更多的条目\n -削弱了清理两个洞穴区域的经验奖励，为两个森林地区增加了经验奖励\n -增强了狼(可能还不够，你们太强大了)\n -其他一些平衡技能的变化，英雄和物品\n -战斗中的敌人现在显示他们的机会击中英雄和躲避英雄的攻击，而不是AP/EP\n -一些风格修复，造型为钱\n -固定父母技能经验增益(现在他们将跟上经验与他们最高级的孩子)\n -增加技能排序(按名称和等级);固定库存分类;你现在可以再次点击按钮改变方向(升序和降序)之间切换\ nv0.3.5a \ n -小CSS修复\ nv0.3.5b \ n -设备显示修复\ n -贸易bug修复\ nv0.3.5c \ n -固定技能奖励两次添加\ nv0.3.5d \ n -一些值不会刷新正确\ n -添加consolelogging一些警告的意想不到的结果\ n \ n -固定一些四舍五入问题——一些平衡的变化\ n -另一个贸易修复\ nv0.3.5e \ n - xp奖金来自父母技能现在包含在经验增益技能提示\n -小的平衡变化\n -固定了一些样式\nv0.3.5f\n -(希望)修复了攻击速度\nv0.3.5g\n的问题-固定了非武装攻击速度奖励没有被添加\nv0.3.5h\n -固定了加载旧的小错误保存\nv0.3.5i\n -固定攻击在0耐力上变得更快",
    "v0.3.4\n    - implemented books (only 2 available for now); both provide small bonuses to xp gains upon finish\nv0.3.4e\n    - huge buff to shield block chance, other balance changes\n    - bugfixes (trade, loading, wrong values in bestiary)\n    - added console message on auto save\n    - added visual distinction to the book that is being read\n    - travel options in locations now don't get grouped if there's nothing other than travel available (e.g. the cave)\n    - modified function for inventory display so it can now not only refresh all items but also a single one\n    - compatibility for saves from older versions\n    - fixed that ugly display of \"def\" in combat\nv0.3.4f\n    - fixed reward of \"tight manouvers\" skill\n    - fixed display of \"stamina efficiency\" reward\n    - fixed issue with area unlocks (didnt work if it was supposed to be unlocked by clearing some combat zone)\n    - minor balance changes\nv0.3.4g\n    - fixed wrong rounding of dropchances in bestiary\n    - fixed lack of rounding in reading time\n    - fixed xp gains from harder areas\n    - removed underscores from some descriptions\n    - slightly nerfed some xp bonuses\nv0.3.4h\n    - fixed shield block chance reaching 100% way too soon\n    - fixed block chance display in combat\n    - added game version to save file, for future usage\nv0.3.4i\n    - now can take less than 1 dmg from an attack, if using a shield\n    - rounded some dmg numbers\nv0.3.4i-2\n    - minor fix to CSS": "V0.3.4 \n -实现的书籍(目前只有2个可用);两者都提供了小奖金的经验增益后完成\nv0.3.4e\n -巨大的buff盾格挡的机会，其他平衡变化\n -错误修复(贸易，装载，错误的值在动物寓言集)\ n -添加控制台消息自动保存\ n -添加视觉区别正在读的那本书\ n -旅游选择的位置现在不要分组比旅游如果没有什么其他可用(如洞穴)\ n -库存显示它现在可以修改函数不仅刷新所有项目,而且一个\ n -兼容旧版本的保存\ n -固定丑陋显示的\“def \”在战斗\ nv0.3.4f \ n -固定回报的技能\ n \“紧manouvers \”——固定显示的\“耐力效率\”奖励\ n -固定问题区域解锁(没有工作如果是应该被清理一些战区)解锁\ n -小平衡变化\ nv0.3.4g \ n -固定错误的舍入的动物寓言集dropchances \ n -固定阅读时间缺乏舍入\ n - xp固定收益从困难地区一些描述\ n \ n -删除下划线——有稍微惩罚一些xp奖金\ nv0.3.4h \ n -固定块盾牌机会达到100%的方式太快\n -固定方块的机会显示在战斗\n -添加了游戏版本来保存文件，以供将来使用\nv0.3.4i\n -现在可以采取少于1 dmg的攻击，如果使用盾牌\n -四角一些dmg数字\nv0.3.4i-2\n -小修复CSS",
    "v0.3.3\n    - rebalanced stat gains from skill milestones\n    - added another combat location between infested field and cave depths, to smooth the progression\n    - skill groups replaced with parent skills; now they only provide xp bonus and their child skills have their own milestones\n    - refactored calculations of stats from skills/milestones/equipment/level to a more manageable form\n    - refactored equipment stat calculations\n    - implemented xp bonuses (for now only from skill milestones)": "V0.3.3重新平衡了技能里程碑的属性收益-在被感染的领域和洞穴深度之间添加了另一个战斗位置，以平滑进展-技能组被父技能取代;现在他们只提供经验奖励，他们的孩子技能有自己的里程碑\n -从技能/里程碑/装备/水平的统计重构计算到一个更易于管理的形式\n -重构的装备统计计算\n -实现经验奖励(目前仅从技能里程碑)",
    "v0.3\n    - drop chance now scales with how many of specific enemy were killed, down to 1/10th at 999+\n    - fixed minor bugs when trading stackable items\n    - changed the starting year to 1000\n    - location choices now get foldered only when there's more than two (used to be at more than one)\n    - equipment prices increased by ~50%\n    - introduced bestiary with list of all killed enemies (killcount, description, stats, drops their chances)\n    - rebalanced \"sleeping\" skill rewards\nv0.3b\n    - fixed wrong milestone levels on weapon skills after loading game\n    - changed xp scaling of some skills\n    - fixed wrong calculations on shield blocking skill\nv0.3c\n    - fixed a minor error when loading save with any skill having less xp than needed to be visible\n    - changed the way savefiles are loaded to avoid a bunch of issues": "V0.3 \n -掉落的机会现在缩放多少特定的敌人被杀死，下降到1/10在999+\n -修正了小错误时交易可堆叠的物品\n -改变了开始的一年到1000\n -位置选择现在得到折叠只有当有两个以上(过去是在一个以上)\n -装备价格增加了~50%\n -引入了野兽与所有杀死的敌人的列表(杀戮计数，描述，统计，掉落他们的机会)\n -重新平衡\“睡眠\”技能奖励\nv0.3b\n -修正了错误的里程碑水平上的武器技能加载游戏后\n -改变了一些技能的经验缩放\n -修正了错误的计算上的盾牌阻挡技能\nv0.3c\n -修正了一个小错误时加载保存与任何技能有少于需要的经验可见\n -改变了方式保存文件加载以避免一堆问题",
    "v0.2.9\n    - added \"iron skin\" skill that provides a tiny bit of def, xp is gained for fighting with no armour equipped\n    - evasion xp is increased by 50% when fighting with no armor equipped (let's call it an adrenaline bonus)\n    - changed the hit-chance formula to non-linear\nv0.2.9b\n    - \"iron skin\" now works\n    - minor fixes to some formulas": "V0.2.9 \n -增加了\“铁皮\”技能，提供了一点点防御，xp是获得战斗没有装甲装备\n -逃避经验增加50%时战斗没有装甲装备(让我们称之为肾上腺素加成)\n -改变了命中几率公式非线性\nv0.2.9 \n - \“铁皮\”现在工作\n -小修正了一些公式",
    "v0.2.8\n    - message log can now be filtered for stuff related to combat/levelups&unlocks/events/loot\n    - now if there's more than 1 option in any category (work, train, travel, talk, trade), \n      it's available via separate list of choices instead of all being crammed together\n    - rounded displayed values for some skill effects": "V0.2.8 \n -消息日志现在可以过滤与战斗/升级和解锁/事件/战利品相关的东西\n -现在如果在任何类别(工作，火车，旅行，谈话，贸易)中有超过1个选项，\n它可以通过单独的选择列表而不是全部挤在一起\n -四舍五入显示一些技能效果的值",
    "v0.2.7\n    - reworked the location type system\n    - payments for some jobs are now affected by related skill\n    - moved dialogue answers to dialouge box (instead of message log)": "V0.2.7 \n -重做了位置类型系统\n -一些工作的报酬现在受到相关技能的影响\n -移动对话回答对话框(而不是消息日志)",
    "v0.2.5\n    - modified tooltip positioning so that they don't leave the screen\n    - rounded some displayed numbers\n    - slightly weakened first enemy type\n    - some minor bugfixes": "V0.2.5 \n -修改了工具提示的定位，以便他们不会离开屏幕\n -四舍五入一些显示的数字\n -略微削弱了第一个敌人类型\n -一些小bug修复",
    "v0.2.4\n    - introduced location types (for combat zones), that bring some additional penalties to hit/evasion chance\n    - added a new job, unlocked after clearing 2nd combat zone": "V0.2.4 \n -引入位置类型(为战区)，带来一些额外的惩罚命中/逃避的机会\n -增加了一个新的工作，在清除第二个战区后解锁",
    "v0.2.2\n    - fixed issue where multi-enemy locations required killing X enemies, instead of killing X enemy groups\n    - implemented stamina effects on character's attack speed and attack power\n    - number of [alive] enemies now has negative impact on character's hit chance\n    - number of enemies multiplies gained character xp by sqrt of group size\n    - new training activity": "v0.2.2\n -修复了多个敌人位置需要杀死X个敌人的问题，而不是杀死X个敌人团体\n -对角色的攻击速度和攻击力\n -[活着的]敌人的数量现在对角色的命中几率\n -敌人数量乘以获得的角色xp的根号\n -新的训练活动",
    "v0.2.1\n    - fixed two small problems when importing file\n    - fixed issue with combat being paused when area page is hidden\n    - rewrote the combat loops, made it work properly when tab is not focused": "V0.2.1 \n -修正了两个小问题，当导入文件\n -修正了战斗被暂停时，区域页面隐藏\n -重写了战斗循环，使它正常工作时，TAB没有聚焦",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);